package org.thingml.debraquisition;

import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import jssc.SerialPortList;
import org.thingml.rtcharts.swing.*;

/**
 *
 * @author franck
 */
public class MainFrame extends javax.swing.JFrame implements DataListener {

    GraphBuffer last120 = new GraphBuffer(120);
    GraphBuffer last1200 = new GraphBuffer(1200);
    GraphBuffer last14400 = new GraphBuffer(14400);
    
    SerialDriver driver;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        ((GraphPanel)jPanelG0).start();
        ((GraphPanel)jPanelG1).setSleepTime(1000);
        ((GraphPanel)jPanelG1).start();
        ((GraphPanel)jPanelG2).setSleepTime(5000);
        ((GraphPanel)jPanelG2).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBoxDevice = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanelG1 = new LineGraphPanel(last1200, "[:Ch0] (last 20 min)", 0, 1024, 256, new java.awt.Color(0, 153, 255));
        jPanelG2 = new LineGraphPanel(last14400, "[:Ch0] (last 4 hours)", 0, 1024, 256, new java.awt.Color(0, 153, 255));
        jPanelG0 = new LineGraphPanel(last120, "[:Ch0] (last 2 min)", 0, 1024, 256, new java.awt.Color(0, 153, 255));
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DebrAquisition Pro (Limited Edition)");

        jLabel1.setText("Input Device :");

        jComboBoxDevice.setEditable(true);

        jButton1.setText("Connect");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Detect Devices...");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Start File Capture...");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setText("Not Connected.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelG1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelG0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelG2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxDevice, 0, 422, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxDevice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelG0, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelG1, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelG2, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jLabel2)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if (driver != null) { // this is a diconnect
            if (fileLogger != null) stopCapture();
            driver.disconnect();
            driver.clearDataListeners();
            driver = null;
            jButton1.setText(" Connect ");
            jComboBoxDevice.setEnabled(true);
            jButton2.setEnabled(true);
            jLabel2.setText("Not Connected.");
            jButton3.setEnabled(false);
        }
        else { // This is a connect
            String port = jComboBoxDevice.getSelectedItem().toString();
            driver = new SerialDriver();
            driver.addDataListener(this);
            if (driver.connect(port)) {
                jButton1.setText("Disconnect");
                jComboBoxDevice.setEnabled(false);
                jButton2.setEnabled(false);
                jLabel2.setText("Connected to device " + port);
                jButton3.setEnabled(true);
            }
            else {
                System.err.println("Error connecting to device " + port);
                jLabel2.setText("Error connecting to device " + port);
                driver.disconnect();
                driver.clearDataListeners();
                driver = null;
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String[] portNames = SerialPortList.getPortNames();
        jComboBoxDevice.setModel(new DefaultComboBoxModel(portNames));
    }//GEN-LAST:event_jButton2ActionPerformed

    FileLogger fileLogger = null;
    JFileChooser j = new JFileChooser();
    
    private void stopCapture() {
         fileLogger.close();
        driver.removeDataListener(fileLogger);
        fileLogger = null;
        jButton3.setText("Start File Capture...");
        jLabel2.setText("Capture Stopped.");
    }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        if (fileLogger != null) { // Stopping
           stopCapture();
        }
        else { // Start loggging
            
            j.setDialogTitle("Select Ouput Directory...");
            j.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            Integer opt = j.showSaveDialog(this);
            if (opt == JFileChooser.APPROVE_OPTION) {
                try {
                    File folder = j.getSelectedFile();
                    File file = new File(folder, "Ch0_" + (new SimpleDateFormat("yyyyMMddhhmmss").format(new Date())) + ".csv");
                    fileLogger = new FileLogger(file);
                    jLabel2.setText("Capturing in " + file.getAbsolutePath());
                } catch (IOException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                    jLabel2.setText("Error creating log file !");
                    return;
                }
                driver.addDataListener(fileLogger);
                jButton3.setText("- Stop File Capture -");
            }
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBoxDevice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelG0;
    private javax.swing.JPanel jPanelG1;
    private javax.swing.JPanel jPanelG2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void incomingValue(String name, int value) {
        if (name.equals("ch0")) {
            last120.insertData(value);
            last1200.insertData(value);
            last14400.insertData(value);
        }
    }
}
