
/***************************************************************************** 
 * File generated from ThingML (Do not edit this file) 
 *****************************************************************************/


/*****************************************************************************
 * Definition of simple types and enumerations
 *****************************************************************************/

// Definition of Enumeration  DigitalState
#define DIGITALSTATE_LOW 0
#define DIGITALSTATE_HIGH 1

// Definition of Enumeration  DigitalState
#define DIGITALSTATE_LOW 0
#define DIGITALSTATE_HIGH 1

/*****************************************************************************
 * Headers for type : Adafruit_1_8pLCDShieldShield
 *****************************************************************************/


// BEGIN: Code from the c_header annotation Adafruit_1_8pLCDShieldShield

#include <Adafruit_GFX.h>    // Core graphics library
#include <Adafruit_ST7735.h> // Hardware-specific library
#include <SPI.h>
#define TFT_CS 10
#define TFT_RST 9
#define TFT_DC 8
#define TFT_SCLK 13
#define TFT_MOSI 11
// END: Code from the c_header annotation Adafruit_1_8pLCDShieldShield

// Definition of the instance stuct:
struct Adafruit_1_8pLCDShieldShield_Instance {
// Variables for the ID of the instance
int id;
// Variables for the current instance state
int Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_State;
// Variables for the properties of the instance
uint8_t Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_bpin__var;
uint8_t Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_Idle_bstate__var;
};

// Declaration of prototypes outgoing messages:
void Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_OnEntry(int state, struct Adafruit_1_8pLCDShieldShield_Instance *_instance);
void Adafruit_1_8pLCDShieldShield_handle_lcd_set_cursor(struct Adafruit_1_8pLCDShieldShield_Instance *_instance, uint8_t c, uint8_t l);
void Adafruit_1_8pLCDShieldShield_handle_lcd_drawRect(struct Adafruit_1_8pLCDShieldShield_Instance *_instance, uint16_t x, uint16_t y, uint16_t w, uint16_t l, uint16_t col);
void Adafruit_1_8pLCDShieldShield_handle_lcd_fillRect(struct Adafruit_1_8pLCDShieldShield_Instance *_instance, uint16_t x, uint16_t y, uint16_t w, uint16_t l, uint16_t col);
void Adafruit_1_8pLCDShieldShield_handle_lcd_print_dec(struct Adafruit_1_8pLCDShieldShield_Instance *_instance, double num);
void Adafruit_1_8pLCDShieldShield_handle_lcd_print_str(struct Adafruit_1_8pLCDShieldShield_Instance *_instance, char * msg);
void Adafruit_1_8pLCDShieldShield_handle_lcd_print_num(struct Adafruit_1_8pLCDShieldShield_Instance *_instance, int16_t num);
void Adafruit_1_8pLCDShieldShield_handle_lcd_clear(struct Adafruit_1_8pLCDShieldShield_Instance *_instance);
void Adafruit_1_8pLCDShieldShield_handle_button_button_state(struct Adafruit_1_8pLCDShieldShield_Instance *_instance);
void Adafruit_1_8pLCDShieldShield_handle_arduino_ready(struct Adafruit_1_8pLCDShieldShield_Instance *_instance);
void Adafruit_1_8pLCDShieldShield_handle_arduino_100ms_interrupt(struct Adafruit_1_8pLCDShieldShield_Instance *_instance);
void Adafruit_1_8pLCDShieldShield_handle_arduino_readAnalogResponse(struct Adafruit_1_8pLCDShieldShield_Instance *_instance, uint8_t pin, int res);
// Declaration of callbacks for incomming messages:
void register_Adafruit_1_8pLCDShieldShield_send_arduino_setInput_listener(void (*_listener)(struct Adafruit_1_8pLCDShieldShield_Instance*, uint8_t));
void register_Adafruit_1_8pLCDShieldShield_send_arduino_readAnalog_listener(void (*_listener)(struct Adafruit_1_8pLCDShieldShield_Instance*, uint8_t));
void register_Adafruit_1_8pLCDShieldShield_send_arduino_serial_print_str_listener(void (*_listener)(struct Adafruit_1_8pLCDShieldShield_Instance*, char *));
void register_Adafruit_1_8pLCDShieldShield_send_button_button_state_response_listener(void (*_listener)(struct Adafruit_1_8pLCDShieldShield_Instance*, uint8_t));
void register_Adafruit_1_8pLCDShieldShield_send_button_button_state_change_listener(void (*_listener)(struct Adafruit_1_8pLCDShieldShield_Instance*, uint8_t));
void register_Adafruit_1_8pLCDShieldShield_send_lcd_LCDready_listener(void (*_listener)(struct Adafruit_1_8pLCDShieldShield_Instance*));

// Definition of the states:
#define ADAFRUIT_1_8PLCDSHIELDSHIELD_RGBLCDSHIELDSM_STATE 0
#define ADAFRUIT_1_8PLCDSHIELDSHIELD_RGBLCDSHIELDSM_EMPTY_STATE 1
#define ADAFRUIT_1_8PLCDSHIELDSHIELD_RGBLCDSHIELDSM_SETUP_STATE 2
#define ADAFRUIT_1_8PLCDSHIELDSHIELD_RGBLCDSHIELDSM_IDLE_STATE 3

/*****************************************************************************
 * Implementation for type : Adafruit_1_8pLCDShieldShield
 *****************************************************************************/


// BEGIN: Code from the c_global annotation Adafruit_1_8pLCDShieldShield

Adafruit_ST7735 tft = Adafruit_ST7735(TFT_CS,  TFT_DC, TFT_RST);

// END: Code from the c_global annotation Adafruit_1_8pLCDShieldShield

// Declaration of prototypes:
#ifdef EXTERN_C_PROTOTYPES
extern "C" {
#endif
void Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_OnExit(int state, struct Adafruit_1_8pLCDShieldShield_Instance *_instance);
void Adafruit_1_8pLCDShieldShield_send_arduino_setInput(struct Adafruit_1_8pLCDShieldShield_Instance *_instance, uint8_t pin);
void Adafruit_1_8pLCDShieldShield_send_arduino_readAnalog(struct Adafruit_1_8pLCDShieldShield_Instance *_instance, uint8_t pin);
void Adafruit_1_8pLCDShieldShield_send_arduino_serial_print_str(struct Adafruit_1_8pLCDShieldShield_Instance *_instance, char * msg);
void Adafruit_1_8pLCDShieldShield_send_button_button_state_response(struct Adafruit_1_8pLCDShieldShield_Instance *_instance, uint8_t bstate);
void Adafruit_1_8pLCDShieldShield_send_button_button_state_change(struct Adafruit_1_8pLCDShieldShield_Instance *_instance, uint8_t bstate);
void Adafruit_1_8pLCDShieldShield_send_lcd_LCDready(struct Adafruit_1_8pLCDShieldShield_Instance *_instance);
#ifdef EXTERN_C_PROTOTYPES
}
#endif

// Declaration of functions:

// On Entry Actions:
void Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_OnEntry(int state, struct Adafruit_1_8pLCDShieldShield_Instance *_instance) {
switch(state) {
case ADAFRUIT_1_8PLCDSHIELDSHIELD_RGBLCDSHIELDSM_STATE:
_instance->Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_State = ADAFRUIT_1_8PLCDSHIELDSHIELD_RGBLCDSHIELDSM_EMPTY_STATE;
{
}
Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_OnEntry(_instance->Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_State, _instance);
break;
case ADAFRUIT_1_8PLCDSHIELDSHIELD_RGBLCDSHIELDSM_EMPTY_STATE:
break;
case ADAFRUIT_1_8PLCDSHIELDSHIELD_RGBLCDSHIELDSM_SETUP_STATE:
{
Adafruit_1_8pLCDShieldShield_send_arduino_setInput(_instance, _instance->Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_bpin__var);
tft.initR(INITR_BLACKTAB);
			tft.fillScreen(0x0000);
			tft.setTextColor(0xFFFF);
}
break;
case ADAFRUIT_1_8PLCDSHIELDSHIELD_RGBLCDSHIELDSM_IDLE_STATE:
break;
default: break;
}
}

// On Exit Actions:
void Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_OnExit(int state, struct Adafruit_1_8pLCDShieldShield_Instance *_instance) {
switch(state) {
case ADAFRUIT_1_8PLCDSHIELDSHIELD_RGBLCDSHIELDSM_STATE:
Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_OnExit(_instance->Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_State, _instance);
break;
case ADAFRUIT_1_8PLCDSHIELDSHIELD_RGBLCDSHIELDSM_EMPTY_STATE:
break;
case ADAFRUIT_1_8PLCDSHIELDSHIELD_RGBLCDSHIELDSM_SETUP_STATE:
break;
case ADAFRUIT_1_8PLCDSHIELDSHIELD_RGBLCDSHIELDSM_IDLE_STATE:
break;
default: break;
}
}

// Event Handlers for incoming messages:
void Adafruit_1_8pLCDShieldShield_handle_lcd_set_cursor(struct Adafruit_1_8pLCDShieldShield_Instance *_instance, uint8_t c, uint8_t l) {
uint8_t Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_State_event_consumed = 0;
if (_instance->Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_State == ADAFRUIT_1_8PLCDSHIELDSHIELD_RGBLCDSHIELDSM_IDLE_STATE) {
if (Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_State_event_consumed == 0 && 1) {
tft.setCursor(c, l);
Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_State_event_consumed = 1;
}
}
}
void Adafruit_1_8pLCDShieldShield_handle_lcd_drawRect(struct Adafruit_1_8pLCDShieldShield_Instance *_instance, uint16_t x, uint16_t y, uint16_t w, uint16_t l, uint16_t col) {
uint8_t Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_State_event_consumed = 0;
if (_instance->Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_State == ADAFRUIT_1_8PLCDSHIELDSHIELD_RGBLCDSHIELDSM_IDLE_STATE) {
if (Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_State_event_consumed == 0 && 1) {
tft.drawRect(x,y,w,l,col);
Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_State_event_consumed = 1;
}
}
}
void Adafruit_1_8pLCDShieldShield_handle_lcd_fillRect(struct Adafruit_1_8pLCDShieldShield_Instance *_instance, uint16_t x, uint16_t y, uint16_t w, uint16_t l, uint16_t col) {
uint8_t Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_State_event_consumed = 0;
if (_instance->Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_State == ADAFRUIT_1_8PLCDSHIELDSHIELD_RGBLCDSHIELDSM_IDLE_STATE) {
if (Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_State_event_consumed == 0 && 1) {
tft.fillRect(x,y,w,l,col);
Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_State_event_consumed = 1;
}
}
}
void Adafruit_1_8pLCDShieldShield_handle_lcd_print_dec(struct Adafruit_1_8pLCDShieldShield_Instance *_instance, double num) {
uint8_t Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_State_event_consumed = 0;
if (_instance->Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_State == ADAFRUIT_1_8PLCDSHIELDSHIELD_RGBLCDSHIELDSM_IDLE_STATE) {
if (Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_State_event_consumed == 0 && 1) {
tft.print(num);
Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_State_event_consumed = 1;
}
}
}
void Adafruit_1_8pLCDShieldShield_handle_lcd_print_str(struct Adafruit_1_8pLCDShieldShield_Instance *_instance, char * msg) {
uint8_t Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_State_event_consumed = 0;
if (_instance->Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_State == ADAFRUIT_1_8PLCDSHIELDSHIELD_RGBLCDSHIELDSM_IDLE_STATE) {
if (Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_State_event_consumed == 0 && 1) {
tft.print(msg);
Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_State_event_consumed = 1;
}
}
}
void Adafruit_1_8pLCDShieldShield_handle_lcd_print_num(struct Adafruit_1_8pLCDShieldShield_Instance *_instance, int16_t num) {
uint8_t Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_State_event_consumed = 0;
if (_instance->Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_State == ADAFRUIT_1_8PLCDSHIELDSHIELD_RGBLCDSHIELDSM_IDLE_STATE) {
if (Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_State_event_consumed == 0 && 1) {
tft.print(num);
Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_State_event_consumed = 1;
}
}
}
void Adafruit_1_8pLCDShieldShield_handle_lcd_clear(struct Adafruit_1_8pLCDShieldShield_Instance *_instance) {
uint8_t Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_State_event_consumed = 0;
if (_instance->Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_State == ADAFRUIT_1_8PLCDSHIELDSHIELD_RGBLCDSHIELDSM_IDLE_STATE) {
if (Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_State_event_consumed == 0 && 1) {
tft.fillScreen(0x0000);
Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_State_event_consumed = 1;
}
}
}
void Adafruit_1_8pLCDShieldShield_handle_button_button_state(struct Adafruit_1_8pLCDShieldShield_Instance *_instance) {
uint8_t Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_State_event_consumed = 0;
if (_instance->Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_State == ADAFRUIT_1_8PLCDSHIELDSHIELD_RGBLCDSHIELDSM_IDLE_STATE) {
if (Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_State_event_consumed == 0 && 1) {
{
Adafruit_1_8pLCDShieldShield_send_button_button_state_response(_instance, _instance->Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_Idle_bstate__var);
}
Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_State_event_consumed = 1;
}
}
}
void Adafruit_1_8pLCDShieldShield_handle_arduino_ready(struct Adafruit_1_8pLCDShieldShield_Instance *_instance) {
uint8_t Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_State_event_consumed = 0;
if (_instance->Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_State == ADAFRUIT_1_8PLCDSHIELDSHIELD_RGBLCDSHIELDSM_EMPTY_STATE) {
if (Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_State_event_consumed == 0 && 1) {
Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_OnExit(ADAFRUIT_1_8PLCDSHIELDSHIELD_RGBLCDSHIELDSM_EMPTY_STATE, _instance);
_instance->Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_State = ADAFRUIT_1_8PLCDSHIELDSHIELD_RGBLCDSHIELDSM_SETUP_STATE;
Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_OnEntry(ADAFRUIT_1_8PLCDSHIELDSHIELD_RGBLCDSHIELDSM_SETUP_STATE, _instance);
Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_State_event_consumed = 1;
}
}
}
void Adafruit_1_8pLCDShieldShield_handle_arduino_100ms_interrupt(struct Adafruit_1_8pLCDShieldShield_Instance *_instance) {
uint8_t Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_State_event_consumed = 0;
if (_instance->Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_State == ADAFRUIT_1_8PLCDSHIELDSHIELD_RGBLCDSHIELDSM_IDLE_STATE) {
if (Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_State_event_consumed == 0 && 1) {
{
Adafruit_1_8pLCDShieldShield_send_arduino_readAnalog(_instance, _instance->Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_bpin__var);
}
Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_State_event_consumed = 1;
}
}
}
void Adafruit_1_8pLCDShieldShield_handle_arduino_readAnalogResponse(struct Adafruit_1_8pLCDShieldShield_Instance *_instance, uint8_t pin, int res) {
uint8_t Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_State_event_consumed = 0;
if (_instance->Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_State == ADAFRUIT_1_8PLCDSHIELDSHIELD_RGBLCDSHIELDSM_IDLE_STATE) {
if (Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_State_event_consumed == 0 && 1) {
{
int joystickState =res;
				int bstatetmp = 0;
			    if (joystickState < 50) {bstatetmp = 1;}
			    else if (joystickState < 150) {bstatetmp = 2;}
			    else if (joystickState < 250) {bstatetmp = 3;}
			    else if (joystickState < 500) {bstatetmp = 4;}
			    else if (joystickState < 650) {bstatetmp = 5;}
if( !(_instance->Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_Idle_bstate__var == bstatetmp)) {
_instance->Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_Idle_bstate__var = bstatetmp;
Adafruit_1_8pLCDShieldShield_send_button_button_state_change(_instance, _instance->Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_Idle_bstate__var);
}
_instance->Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_Idle_bstate__var = bstatetmp;
}
Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_State_event_consumed = 1;
}
}
}
void Adafruit_1_8pLCDShieldShield_handle_empty_event(struct Adafruit_1_8pLCDShieldShield_Instance *_instance) {
if (_instance->Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_State == ADAFRUIT_1_8PLCDSHIELDSHIELD_RGBLCDSHIELDSM_SETUP_STATE) {
if (1) {
Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_OnExit(ADAFRUIT_1_8PLCDSHIELDSHIELD_RGBLCDSHIELDSM_SETUP_STATE, _instance);
_instance->Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_State = ADAFRUIT_1_8PLCDSHIELDSHIELD_RGBLCDSHIELDSM_IDLE_STATE;
{
Adafruit_1_8pLCDShieldShield_send_arduino_serial_print_str(_instance, "[LCD shield] Ready\n");
Adafruit_1_8pLCDShieldShield_send_lcd_LCDready(_instance);
}
Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_OnEntry(ADAFRUIT_1_8PLCDSHIELDSHIELD_RGBLCDSHIELDSM_IDLE_STATE, _instance);
}
}
}

// Observers for outgoing messages:
void (*Adafruit_1_8pLCDShieldShield_send_arduino_setInput_listener)(struct Adafruit_1_8pLCDShieldShield_Instance*, uint8_t)= 0x0;
void register_Adafruit_1_8pLCDShieldShield_send_arduino_setInput_listener(void (*_listener)(struct Adafruit_1_8pLCDShieldShield_Instance*, uint8_t)){
Adafruit_1_8pLCDShieldShield_send_arduino_setInput_listener = _listener;
}
void Adafruit_1_8pLCDShieldShield_send_arduino_setInput(struct Adafruit_1_8pLCDShieldShield_Instance *_instance, uint8_t pin){
if (Adafruit_1_8pLCDShieldShield_send_arduino_setInput_listener != 0x0) Adafruit_1_8pLCDShieldShield_send_arduino_setInput_listener(_instance, pin);
}
void (*Adafruit_1_8pLCDShieldShield_send_arduino_readAnalog_listener)(struct Adafruit_1_8pLCDShieldShield_Instance*, uint8_t)= 0x0;
void register_Adafruit_1_8pLCDShieldShield_send_arduino_readAnalog_listener(void (*_listener)(struct Adafruit_1_8pLCDShieldShield_Instance*, uint8_t)){
Adafruit_1_8pLCDShieldShield_send_arduino_readAnalog_listener = _listener;
}
void Adafruit_1_8pLCDShieldShield_send_arduino_readAnalog(struct Adafruit_1_8pLCDShieldShield_Instance *_instance, uint8_t pin){
if (Adafruit_1_8pLCDShieldShield_send_arduino_readAnalog_listener != 0x0) Adafruit_1_8pLCDShieldShield_send_arduino_readAnalog_listener(_instance, pin);
}
void (*Adafruit_1_8pLCDShieldShield_send_arduino_serial_print_str_listener)(struct Adafruit_1_8pLCDShieldShield_Instance*, char *)= 0x0;
void register_Adafruit_1_8pLCDShieldShield_send_arduino_serial_print_str_listener(void (*_listener)(struct Adafruit_1_8pLCDShieldShield_Instance*, char *)){
Adafruit_1_8pLCDShieldShield_send_arduino_serial_print_str_listener = _listener;
}
void Adafruit_1_8pLCDShieldShield_send_arduino_serial_print_str(struct Adafruit_1_8pLCDShieldShield_Instance *_instance, char * msg){
if (Adafruit_1_8pLCDShieldShield_send_arduino_serial_print_str_listener != 0x0) Adafruit_1_8pLCDShieldShield_send_arduino_serial_print_str_listener(_instance, msg);
}
void (*Adafruit_1_8pLCDShieldShield_send_button_button_state_response_listener)(struct Adafruit_1_8pLCDShieldShield_Instance*, uint8_t)= 0x0;
void register_Adafruit_1_8pLCDShieldShield_send_button_button_state_response_listener(void (*_listener)(struct Adafruit_1_8pLCDShieldShield_Instance*, uint8_t)){
Adafruit_1_8pLCDShieldShield_send_button_button_state_response_listener = _listener;
}
void Adafruit_1_8pLCDShieldShield_send_button_button_state_response(struct Adafruit_1_8pLCDShieldShield_Instance *_instance, uint8_t bstate){
if (Adafruit_1_8pLCDShieldShield_send_button_button_state_response_listener != 0x0) Adafruit_1_8pLCDShieldShield_send_button_button_state_response_listener(_instance, bstate);
}
void (*Adafruit_1_8pLCDShieldShield_send_button_button_state_change_listener)(struct Adafruit_1_8pLCDShieldShield_Instance*, uint8_t)= 0x0;
void register_Adafruit_1_8pLCDShieldShield_send_button_button_state_change_listener(void (*_listener)(struct Adafruit_1_8pLCDShieldShield_Instance*, uint8_t)){
Adafruit_1_8pLCDShieldShield_send_button_button_state_change_listener = _listener;
}
void Adafruit_1_8pLCDShieldShield_send_button_button_state_change(struct Adafruit_1_8pLCDShieldShield_Instance *_instance, uint8_t bstate){
if (Adafruit_1_8pLCDShieldShield_send_button_button_state_change_listener != 0x0) Adafruit_1_8pLCDShieldShield_send_button_button_state_change_listener(_instance, bstate);
}
void (*Adafruit_1_8pLCDShieldShield_send_lcd_LCDready_listener)(struct Adafruit_1_8pLCDShieldShield_Instance*)= 0x0;
void register_Adafruit_1_8pLCDShieldShield_send_lcd_LCDready_listener(void (*_listener)(struct Adafruit_1_8pLCDShieldShield_Instance*)){
Adafruit_1_8pLCDShieldShield_send_lcd_LCDready_listener = _listener;
}
void Adafruit_1_8pLCDShieldShield_send_lcd_LCDready(struct Adafruit_1_8pLCDShieldShield_Instance *_instance){
if (Adafruit_1_8pLCDShieldShield_send_lcd_LCDready_listener != 0x0) Adafruit_1_8pLCDShieldShield_send_lcd_LCDready_listener(_instance);
}

/*****************************************************************************
 * Headers for type : ArduinoSketch
 *****************************************************************************/

// Definition of the instance stuct:
struct ArduinoSketch_Instance {
// Variables for the ID of the instance
int id;
// Variables for the current instance state
int ArduinoSketch_ArduinoSketchStateChart_State;
// Variables for the properties of the instance
uint8_t ArduinoSketch_Sensor__var;
uint8_t ArduinoSketch_ArduinoSketchStateChart_PLOT_cpt__var;
uint8_t ArduinoSketch_ArduinoSketchStateChart_PLOT_MAX__var;
};

// Declaration of prototypes outgoing messages:
void ArduinoSketch_ArduinoSketchStateChart_OnEntry(int state, struct ArduinoSketch_Instance *_instance);
void ArduinoSketch_handle_arduino_100ms_interrupt(struct ArduinoSketch_Instance *_instance);
void ArduinoSketch_handle_arduino_readAnalogResponse(struct ArduinoSketch_Instance *_instance, uint8_t pin, int res);
void ArduinoSketch_handle_lcd_LCDready(struct ArduinoSketch_Instance *_instance);
// Declaration of callbacks for incomming messages:
void register_ArduinoSketch_send_button_button_state_listener(void (*_listener)(struct ArduinoSketch_Instance*));
void register_ArduinoSketch_send_lcd_print_num_listener(void (*_listener)(struct ArduinoSketch_Instance*, int16_t));
void register_ArduinoSketch_send_lcd_print_dec_listener(void (*_listener)(struct ArduinoSketch_Instance*, double));
void register_ArduinoSketch_send_lcd_print_str_listener(void (*_listener)(struct ArduinoSketch_Instance*, char *));
void register_ArduinoSketch_send_lcd_clear_listener(void (*_listener)(struct ArduinoSketch_Instance*));
void register_ArduinoSketch_send_lcd_set_cursor_listener(void (*_listener)(struct ArduinoSketch_Instance*, uint8_t, uint8_t));
void register_ArduinoSketch_send_lcd_set_bgcolor_listener(void (*_listener)(struct ArduinoSketch_Instance*, uint8_t));
void register_ArduinoSketch_send_lcd_fillRect_listener(void (*_listener)(struct ArduinoSketch_Instance*, uint16_t, uint16_t, uint16_t, uint16_t, uint16_t));
void register_ArduinoSketch_send_lcd_drawRect_listener(void (*_listener)(struct ArduinoSketch_Instance*, uint16_t, uint16_t, uint16_t, uint16_t, uint16_t));
void register_ArduinoSketch_send_arduino_timer_start_listener(void (*_listener)(struct ArduinoSketch_Instance*, uint8_t, int16_t));
void register_ArduinoSketch_send_arduino_timer_cancel_listener(void (*_listener)(struct ArduinoSketch_Instance*, uint8_t));
void register_ArduinoSketch_send_arduino_serial_print_str_listener(void (*_listener)(struct ArduinoSketch_Instance*, char *));
void register_ArduinoSketch_send_arduino_serial_print_dec_listener(void (*_listener)(struct ArduinoSketch_Instance*, double));
void register_ArduinoSketch_send_arduino_serial_print_num_listener(void (*_listener)(struct ArduinoSketch_Instance*, int16_t));
void register_ArduinoSketch_send_arduino_usb_print_str_listener(void (*_listener)(struct ArduinoSketch_Instance*, char *));
void register_ArduinoSketch_send_arduino_usb_print_dec_listener(void (*_listener)(struct ArduinoSketch_Instance*, double));
void register_ArduinoSketch_send_arduino_usb_print_num_listener(void (*_listener)(struct ArduinoSketch_Instance*, int16_t));
void register_ArduinoSketch_send_arduino_setDigitalHigh_listener(void (*_listener)(struct ArduinoSketch_Instance*, uint8_t));
void register_ArduinoSketch_send_arduino_setDigitalLow_listener(void (*_listener)(struct ArduinoSketch_Instance*, uint8_t));
void register_ArduinoSketch_send_arduino_setOutput_listener(void (*_listener)(struct ArduinoSketch_Instance*, uint8_t));
void register_ArduinoSketch_send_arduino_setInput_listener(void (*_listener)(struct ArduinoSketch_Instance*, uint8_t));
void register_ArduinoSketch_send_arduino_readDigital_listener(void (*_listener)(struct ArduinoSketch_Instance*, uint8_t));
void register_ArduinoSketch_send_arduino_readAnalog_listener(void (*_listener)(struct ArduinoSketch_Instance*, uint8_t));

// Definition of the states:
#define ARDUINOSKETCH_ARDUINOSKETCHSTATECHART_STATE 0
#define ARDUINOSKETCH_ARDUINOSKETCHSTATECHART_INIT_STATE 1
#define ARDUINOSKETCH_ARDUINOSKETCHSTATECHART_PLOT_STATE 2

/*****************************************************************************
 * Implementation for type : ArduinoSketch
 *****************************************************************************/

// Declaration of prototypes:
#ifdef EXTERN_C_PROTOTYPES
extern "C" {
#endif
void ArduinoSketch_ArduinoSketchStateChart_OnExit(int state, struct ArduinoSketch_Instance *_instance);
void ArduinoSketch_send_button_button_state(struct ArduinoSketch_Instance *_instance);
void ArduinoSketch_send_lcd_print_num(struct ArduinoSketch_Instance *_instance, int16_t num);
void ArduinoSketch_send_lcd_print_dec(struct ArduinoSketch_Instance *_instance, double num);
void ArduinoSketch_send_lcd_print_str(struct ArduinoSketch_Instance *_instance, char * msg);
void ArduinoSketch_send_lcd_clear(struct ArduinoSketch_Instance *_instance);
void ArduinoSketch_send_lcd_set_cursor(struct ArduinoSketch_Instance *_instance, uint8_t c, uint8_t l);
void ArduinoSketch_send_lcd_set_bgcolor(struct ArduinoSketch_Instance *_instance, uint8_t color);
void ArduinoSketch_send_lcd_fillRect(struct ArduinoSketch_Instance *_instance, uint16_t x, uint16_t y, uint16_t w, uint16_t l, uint16_t col);
void ArduinoSketch_send_lcd_drawRect(struct ArduinoSketch_Instance *_instance, uint16_t x, uint16_t y, uint16_t w, uint16_t l, uint16_t col);
void ArduinoSketch_send_arduino_timer_start(struct ArduinoSketch_Instance *_instance, uint8_t id, int16_t time);
void ArduinoSketch_send_arduino_timer_cancel(struct ArduinoSketch_Instance *_instance, uint8_t id);
void ArduinoSketch_send_arduino_serial_print_str(struct ArduinoSketch_Instance *_instance, char * msg);
void ArduinoSketch_send_arduino_serial_print_dec(struct ArduinoSketch_Instance *_instance, double num);
void ArduinoSketch_send_arduino_serial_print_num(struct ArduinoSketch_Instance *_instance, int16_t num);
void ArduinoSketch_send_arduino_usb_print_str(struct ArduinoSketch_Instance *_instance, char * msg);
void ArduinoSketch_send_arduino_usb_print_dec(struct ArduinoSketch_Instance *_instance, double num);
void ArduinoSketch_send_arduino_usb_print_num(struct ArduinoSketch_Instance *_instance, int16_t num);
void ArduinoSketch_send_arduino_setDigitalHigh(struct ArduinoSketch_Instance *_instance, uint8_t pin);
void ArduinoSketch_send_arduino_setDigitalLow(struct ArduinoSketch_Instance *_instance, uint8_t pin);
void ArduinoSketch_send_arduino_setOutput(struct ArduinoSketch_Instance *_instance, uint8_t pin);
void ArduinoSketch_send_arduino_setInput(struct ArduinoSketch_Instance *_instance, uint8_t pin);
void ArduinoSketch_send_arduino_readDigital(struct ArduinoSketch_Instance *_instance, uint8_t pin);
void ArduinoSketch_send_arduino_readAnalog(struct ArduinoSketch_Instance *_instance, uint8_t pin);
void f_ArduinoSketch_forward_data(struct ArduinoSketch_Instance *_instance, int16_t v);
void f_ArduinoSketch_display_data(struct ArduinoSketch_Instance *_instance, int16_t v);
#ifdef EXTERN_C_PROTOTYPES
}
#endif

// Declaration of functions:
// Definition of function forward_data
void f_ArduinoSketch_forward_data(struct ArduinoSketch_Instance *_instance, int16_t v) {
{
ArduinoSketch_send_arduino_serial_print_str(_instance, ":ch0=");
ArduinoSketch_send_arduino_serial_print_num(_instance, v);
ArduinoSketch_send_arduino_serial_print_str(_instance, ";\n");
}
}

// Definition of function display_data
void f_ArduinoSketch_display_data(struct ArduinoSketch_Instance *_instance, int16_t v) {
{
ArduinoSketch_send_lcd_fillRect(_instance, 4, 4, 40, 10, 0x0000);
ArduinoSketch_send_lcd_set_cursor(_instance, 6, 12);
ArduinoSketch_send_lcd_print_num(_instance, v);
}
}


// On Entry Actions:
void ArduinoSketch_ArduinoSketchStateChart_OnEntry(int state, struct ArduinoSketch_Instance *_instance) {
switch(state) {
case ARDUINOSKETCH_ARDUINOSKETCHSTATECHART_STATE:
_instance->ArduinoSketch_ArduinoSketchStateChart_State = ARDUINOSKETCH_ARDUINOSKETCHSTATECHART_INIT_STATE;
{
ArduinoSketch_send_arduino_setInput(_instance, _instance->ArduinoSketch_Sensor__var);
}
ArduinoSketch_ArduinoSketchStateChart_OnEntry(_instance->ArduinoSketch_ArduinoSketchStateChart_State, _instance);
break;
case ARDUINOSKETCH_ARDUINOSKETCHSTATECHART_INIT_STATE:
break;
case ARDUINOSKETCH_ARDUINOSKETCHSTATECHART_PLOT_STATE:
_instance->ArduinoSketch_ArduinoSketchStateChart_PLOT_cpt__var = 1;
break;
default: break;
}
}

// On Exit Actions:
void ArduinoSketch_ArduinoSketchStateChart_OnExit(int state, struct ArduinoSketch_Instance *_instance) {
switch(state) {
case ARDUINOSKETCH_ARDUINOSKETCHSTATECHART_STATE:
ArduinoSketch_ArduinoSketchStateChart_OnExit(_instance->ArduinoSketch_ArduinoSketchStateChart_State, _instance);
break;
case ARDUINOSKETCH_ARDUINOSKETCHSTATECHART_INIT_STATE:
break;
case ARDUINOSKETCH_ARDUINOSKETCHSTATECHART_PLOT_STATE:
break;
default: break;
}
}

// Event Handlers for incoming messages:
void ArduinoSketch_handle_arduino_100ms_interrupt(struct ArduinoSketch_Instance *_instance) {
uint8_t ArduinoSketch_ArduinoSketchStateChart_State_event_consumed = 0;
if (1) {
ArduinoSketch_send_arduino_readAnalog(_instance, _instance->ArduinoSketch_Sensor__var);
ArduinoSketch_ArduinoSketchStateChart_State_event_consumed = 1;
}
}
void ArduinoSketch_handle_arduino_readAnalogResponse(struct ArduinoSketch_Instance *_instance, uint8_t pin, int res) {
uint8_t ArduinoSketch_ArduinoSketchStateChart_State_event_consumed = 0;
if (_instance->ArduinoSketch_ArduinoSketchStateChart_State == ARDUINOSKETCH_ARDUINOSKETCHSTATECHART_PLOT_STATE) {
if (ArduinoSketch_ArduinoSketchStateChart_State_event_consumed == 0 && (pin == _instance->ArduinoSketch_Sensor__var)) {
{
f_ArduinoSketch_forward_data(_instance, res);
ArduinoSketch_send_lcd_fillRect(_instance, res / 10, _instance->ArduinoSketch_ArduinoSketchStateChart_PLOT_cpt__var + 1, 1, 1, 0xF800);
_instance->ArduinoSketch_ArduinoSketchStateChart_PLOT_cpt__var = _instance->ArduinoSketch_ArduinoSketchStateChart_PLOT_cpt__var + 1;
if(_instance->ArduinoSketch_ArduinoSketchStateChart_PLOT_cpt__var > 156) {
ArduinoSketch_send_lcd_fillRect(_instance, 2, 2, 124, 156, 0x0000);
_instance->ArduinoSketch_ArduinoSketchStateChart_PLOT_cpt__var = 1;
}
f_ArduinoSketch_display_data(_instance, res);
}
ArduinoSketch_ArduinoSketchStateChart_State_event_consumed = 1;
}
}
}
void ArduinoSketch_handle_lcd_LCDready(struct ArduinoSketch_Instance *_instance) {
uint8_t ArduinoSketch_ArduinoSketchStateChart_State_event_consumed = 0;
if (_instance->ArduinoSketch_ArduinoSketchStateChart_State == ARDUINOSKETCH_ARDUINOSKETCHSTATECHART_INIT_STATE) {
if (ArduinoSketch_ArduinoSketchStateChart_State_event_consumed == 0 && 1) {
ArduinoSketch_ArduinoSketchStateChart_OnExit(ARDUINOSKETCH_ARDUINOSKETCHSTATECHART_INIT_STATE, _instance);
_instance->ArduinoSketch_ArduinoSketchStateChart_State = ARDUINOSKETCH_ARDUINOSKETCHSTATECHART_PLOT_STATE;
{
ArduinoSketch_send_lcd_clear(_instance);
ArduinoSketch_send_lcd_drawRect(_instance, 1, 1, 126, 158, 0xFFFF);
ArduinoSketch_send_lcd_fillRect(_instance, 2, 2, 124, 156, 0x0000);
}
ArduinoSketch_ArduinoSketchStateChart_OnEntry(ARDUINOSKETCH_ARDUINOSKETCHSTATECHART_PLOT_STATE, _instance);
ArduinoSketch_ArduinoSketchStateChart_State_event_consumed = 1;
}
}
}

// Observers for outgoing messages:
void (*ArduinoSketch_send_button_button_state_listener)(struct ArduinoSketch_Instance*)= 0x0;
void register_ArduinoSketch_send_button_button_state_listener(void (*_listener)(struct ArduinoSketch_Instance*)){
ArduinoSketch_send_button_button_state_listener = _listener;
}
void ArduinoSketch_send_button_button_state(struct ArduinoSketch_Instance *_instance){
if (ArduinoSketch_send_button_button_state_listener != 0x0) ArduinoSketch_send_button_button_state_listener(_instance);
}
void (*ArduinoSketch_send_lcd_print_num_listener)(struct ArduinoSketch_Instance*, int16_t)= 0x0;
void register_ArduinoSketch_send_lcd_print_num_listener(void (*_listener)(struct ArduinoSketch_Instance*, int16_t)){
ArduinoSketch_send_lcd_print_num_listener = _listener;
}
void ArduinoSketch_send_lcd_print_num(struct ArduinoSketch_Instance *_instance, int16_t num){
if (ArduinoSketch_send_lcd_print_num_listener != 0x0) ArduinoSketch_send_lcd_print_num_listener(_instance, num);
}
void (*ArduinoSketch_send_lcd_print_dec_listener)(struct ArduinoSketch_Instance*, double)= 0x0;
void register_ArduinoSketch_send_lcd_print_dec_listener(void (*_listener)(struct ArduinoSketch_Instance*, double)){
ArduinoSketch_send_lcd_print_dec_listener = _listener;
}
void ArduinoSketch_send_lcd_print_dec(struct ArduinoSketch_Instance *_instance, double num){
if (ArduinoSketch_send_lcd_print_dec_listener != 0x0) ArduinoSketch_send_lcd_print_dec_listener(_instance, num);
}
void (*ArduinoSketch_send_lcd_print_str_listener)(struct ArduinoSketch_Instance*, char *)= 0x0;
void register_ArduinoSketch_send_lcd_print_str_listener(void (*_listener)(struct ArduinoSketch_Instance*, char *)){
ArduinoSketch_send_lcd_print_str_listener = _listener;
}
void ArduinoSketch_send_lcd_print_str(struct ArduinoSketch_Instance *_instance, char * msg){
if (ArduinoSketch_send_lcd_print_str_listener != 0x0) ArduinoSketch_send_lcd_print_str_listener(_instance, msg);
}
void (*ArduinoSketch_send_lcd_clear_listener)(struct ArduinoSketch_Instance*)= 0x0;
void register_ArduinoSketch_send_lcd_clear_listener(void (*_listener)(struct ArduinoSketch_Instance*)){
ArduinoSketch_send_lcd_clear_listener = _listener;
}
void ArduinoSketch_send_lcd_clear(struct ArduinoSketch_Instance *_instance){
if (ArduinoSketch_send_lcd_clear_listener != 0x0) ArduinoSketch_send_lcd_clear_listener(_instance);
}
void (*ArduinoSketch_send_lcd_set_cursor_listener)(struct ArduinoSketch_Instance*, uint8_t, uint8_t)= 0x0;
void register_ArduinoSketch_send_lcd_set_cursor_listener(void (*_listener)(struct ArduinoSketch_Instance*, uint8_t, uint8_t)){
ArduinoSketch_send_lcd_set_cursor_listener = _listener;
}
void ArduinoSketch_send_lcd_set_cursor(struct ArduinoSketch_Instance *_instance, uint8_t c, uint8_t l){
if (ArduinoSketch_send_lcd_set_cursor_listener != 0x0) ArduinoSketch_send_lcd_set_cursor_listener(_instance, c, l);
}
void (*ArduinoSketch_send_lcd_set_bgcolor_listener)(struct ArduinoSketch_Instance*, uint8_t)= 0x0;
void register_ArduinoSketch_send_lcd_set_bgcolor_listener(void (*_listener)(struct ArduinoSketch_Instance*, uint8_t)){
ArduinoSketch_send_lcd_set_bgcolor_listener = _listener;
}
void ArduinoSketch_send_lcd_set_bgcolor(struct ArduinoSketch_Instance *_instance, uint8_t color){
if (ArduinoSketch_send_lcd_set_bgcolor_listener != 0x0) ArduinoSketch_send_lcd_set_bgcolor_listener(_instance, color);
}
void (*ArduinoSketch_send_lcd_fillRect_listener)(struct ArduinoSketch_Instance*, uint16_t, uint16_t, uint16_t, uint16_t, uint16_t)= 0x0;
void register_ArduinoSketch_send_lcd_fillRect_listener(void (*_listener)(struct ArduinoSketch_Instance*, uint16_t, uint16_t, uint16_t, uint16_t, uint16_t)){
ArduinoSketch_send_lcd_fillRect_listener = _listener;
}
void ArduinoSketch_send_lcd_fillRect(struct ArduinoSketch_Instance *_instance, uint16_t x, uint16_t y, uint16_t w, uint16_t l, uint16_t col){
if (ArduinoSketch_send_lcd_fillRect_listener != 0x0) ArduinoSketch_send_lcd_fillRect_listener(_instance, x, y, w, l, col);
}
void (*ArduinoSketch_send_lcd_drawRect_listener)(struct ArduinoSketch_Instance*, uint16_t, uint16_t, uint16_t, uint16_t, uint16_t)= 0x0;
void register_ArduinoSketch_send_lcd_drawRect_listener(void (*_listener)(struct ArduinoSketch_Instance*, uint16_t, uint16_t, uint16_t, uint16_t, uint16_t)){
ArduinoSketch_send_lcd_drawRect_listener = _listener;
}
void ArduinoSketch_send_lcd_drawRect(struct ArduinoSketch_Instance *_instance, uint16_t x, uint16_t y, uint16_t w, uint16_t l, uint16_t col){
if (ArduinoSketch_send_lcd_drawRect_listener != 0x0) ArduinoSketch_send_lcd_drawRect_listener(_instance, x, y, w, l, col);
}
void (*ArduinoSketch_send_arduino_timer_start_listener)(struct ArduinoSketch_Instance*, uint8_t, int16_t)= 0x0;
void register_ArduinoSketch_send_arduino_timer_start_listener(void (*_listener)(struct ArduinoSketch_Instance*, uint8_t, int16_t)){
ArduinoSketch_send_arduino_timer_start_listener = _listener;
}
void ArduinoSketch_send_arduino_timer_start(struct ArduinoSketch_Instance *_instance, uint8_t id, int16_t time){
if (ArduinoSketch_send_arduino_timer_start_listener != 0x0) ArduinoSketch_send_arduino_timer_start_listener(_instance, id, time);
}
void (*ArduinoSketch_send_arduino_timer_cancel_listener)(struct ArduinoSketch_Instance*, uint8_t)= 0x0;
void register_ArduinoSketch_send_arduino_timer_cancel_listener(void (*_listener)(struct ArduinoSketch_Instance*, uint8_t)){
ArduinoSketch_send_arduino_timer_cancel_listener = _listener;
}
void ArduinoSketch_send_arduino_timer_cancel(struct ArduinoSketch_Instance *_instance, uint8_t id){
if (ArduinoSketch_send_arduino_timer_cancel_listener != 0x0) ArduinoSketch_send_arduino_timer_cancel_listener(_instance, id);
}
void (*ArduinoSketch_send_arduino_serial_print_str_listener)(struct ArduinoSketch_Instance*, char *)= 0x0;
void register_ArduinoSketch_send_arduino_serial_print_str_listener(void (*_listener)(struct ArduinoSketch_Instance*, char *)){
ArduinoSketch_send_arduino_serial_print_str_listener = _listener;
}
void ArduinoSketch_send_arduino_serial_print_str(struct ArduinoSketch_Instance *_instance, char * msg){
if (ArduinoSketch_send_arduino_serial_print_str_listener != 0x0) ArduinoSketch_send_arduino_serial_print_str_listener(_instance, msg);
}
void (*ArduinoSketch_send_arduino_serial_print_dec_listener)(struct ArduinoSketch_Instance*, double)= 0x0;
void register_ArduinoSketch_send_arduino_serial_print_dec_listener(void (*_listener)(struct ArduinoSketch_Instance*, double)){
ArduinoSketch_send_arduino_serial_print_dec_listener = _listener;
}
void ArduinoSketch_send_arduino_serial_print_dec(struct ArduinoSketch_Instance *_instance, double num){
if (ArduinoSketch_send_arduino_serial_print_dec_listener != 0x0) ArduinoSketch_send_arduino_serial_print_dec_listener(_instance, num);
}
void (*ArduinoSketch_send_arduino_serial_print_num_listener)(struct ArduinoSketch_Instance*, int16_t)= 0x0;
void register_ArduinoSketch_send_arduino_serial_print_num_listener(void (*_listener)(struct ArduinoSketch_Instance*, int16_t)){
ArduinoSketch_send_arduino_serial_print_num_listener = _listener;
}
void ArduinoSketch_send_arduino_serial_print_num(struct ArduinoSketch_Instance *_instance, int16_t num){
if (ArduinoSketch_send_arduino_serial_print_num_listener != 0x0) ArduinoSketch_send_arduino_serial_print_num_listener(_instance, num);
}
void (*ArduinoSketch_send_arduino_usb_print_str_listener)(struct ArduinoSketch_Instance*, char *)= 0x0;
void register_ArduinoSketch_send_arduino_usb_print_str_listener(void (*_listener)(struct ArduinoSketch_Instance*, char *)){
ArduinoSketch_send_arduino_usb_print_str_listener = _listener;
}
void ArduinoSketch_send_arduino_usb_print_str(struct ArduinoSketch_Instance *_instance, char * msg){
if (ArduinoSketch_send_arduino_usb_print_str_listener != 0x0) ArduinoSketch_send_arduino_usb_print_str_listener(_instance, msg);
}
void (*ArduinoSketch_send_arduino_usb_print_dec_listener)(struct ArduinoSketch_Instance*, double)= 0x0;
void register_ArduinoSketch_send_arduino_usb_print_dec_listener(void (*_listener)(struct ArduinoSketch_Instance*, double)){
ArduinoSketch_send_arduino_usb_print_dec_listener = _listener;
}
void ArduinoSketch_send_arduino_usb_print_dec(struct ArduinoSketch_Instance *_instance, double num){
if (ArduinoSketch_send_arduino_usb_print_dec_listener != 0x0) ArduinoSketch_send_arduino_usb_print_dec_listener(_instance, num);
}
void (*ArduinoSketch_send_arduino_usb_print_num_listener)(struct ArduinoSketch_Instance*, int16_t)= 0x0;
void register_ArduinoSketch_send_arduino_usb_print_num_listener(void (*_listener)(struct ArduinoSketch_Instance*, int16_t)){
ArduinoSketch_send_arduino_usb_print_num_listener = _listener;
}
void ArduinoSketch_send_arduino_usb_print_num(struct ArduinoSketch_Instance *_instance, int16_t num){
if (ArduinoSketch_send_arduino_usb_print_num_listener != 0x0) ArduinoSketch_send_arduino_usb_print_num_listener(_instance, num);
}
void (*ArduinoSketch_send_arduino_setDigitalHigh_listener)(struct ArduinoSketch_Instance*, uint8_t)= 0x0;
void register_ArduinoSketch_send_arduino_setDigitalHigh_listener(void (*_listener)(struct ArduinoSketch_Instance*, uint8_t)){
ArduinoSketch_send_arduino_setDigitalHigh_listener = _listener;
}
void ArduinoSketch_send_arduino_setDigitalHigh(struct ArduinoSketch_Instance *_instance, uint8_t pin){
if (ArduinoSketch_send_arduino_setDigitalHigh_listener != 0x0) ArduinoSketch_send_arduino_setDigitalHigh_listener(_instance, pin);
}
void (*ArduinoSketch_send_arduino_setDigitalLow_listener)(struct ArduinoSketch_Instance*, uint8_t)= 0x0;
void register_ArduinoSketch_send_arduino_setDigitalLow_listener(void (*_listener)(struct ArduinoSketch_Instance*, uint8_t)){
ArduinoSketch_send_arduino_setDigitalLow_listener = _listener;
}
void ArduinoSketch_send_arduino_setDigitalLow(struct ArduinoSketch_Instance *_instance, uint8_t pin){
if (ArduinoSketch_send_arduino_setDigitalLow_listener != 0x0) ArduinoSketch_send_arduino_setDigitalLow_listener(_instance, pin);
}
void (*ArduinoSketch_send_arduino_setOutput_listener)(struct ArduinoSketch_Instance*, uint8_t)= 0x0;
void register_ArduinoSketch_send_arduino_setOutput_listener(void (*_listener)(struct ArduinoSketch_Instance*, uint8_t)){
ArduinoSketch_send_arduino_setOutput_listener = _listener;
}
void ArduinoSketch_send_arduino_setOutput(struct ArduinoSketch_Instance *_instance, uint8_t pin){
if (ArduinoSketch_send_arduino_setOutput_listener != 0x0) ArduinoSketch_send_arduino_setOutput_listener(_instance, pin);
}
void (*ArduinoSketch_send_arduino_setInput_listener)(struct ArduinoSketch_Instance*, uint8_t)= 0x0;
void register_ArduinoSketch_send_arduino_setInput_listener(void (*_listener)(struct ArduinoSketch_Instance*, uint8_t)){
ArduinoSketch_send_arduino_setInput_listener = _listener;
}
void ArduinoSketch_send_arduino_setInput(struct ArduinoSketch_Instance *_instance, uint8_t pin){
if (ArduinoSketch_send_arduino_setInput_listener != 0x0) ArduinoSketch_send_arduino_setInput_listener(_instance, pin);
}
void (*ArduinoSketch_send_arduino_readDigital_listener)(struct ArduinoSketch_Instance*, uint8_t)= 0x0;
void register_ArduinoSketch_send_arduino_readDigital_listener(void (*_listener)(struct ArduinoSketch_Instance*, uint8_t)){
ArduinoSketch_send_arduino_readDigital_listener = _listener;
}
void ArduinoSketch_send_arduino_readDigital(struct ArduinoSketch_Instance *_instance, uint8_t pin){
if (ArduinoSketch_send_arduino_readDigital_listener != 0x0) ArduinoSketch_send_arduino_readDigital_listener(_instance, pin);
}
void (*ArduinoSketch_send_arduino_readAnalog_listener)(struct ArduinoSketch_Instance*, uint8_t)= 0x0;
void register_ArduinoSketch_send_arduino_readAnalog_listener(void (*_listener)(struct ArduinoSketch_Instance*, uint8_t)){
ArduinoSketch_send_arduino_readAnalog_listener = _listener;
}
void ArduinoSketch_send_arduino_readAnalog(struct ArduinoSketch_Instance *_instance, uint8_t pin){
if (ArduinoSketch_send_arduino_readAnalog_listener != 0x0) ArduinoSketch_send_arduino_readAnalog_listener(_instance, pin);
}

/*****************************************************************************
 * Headers for type : ArduinoScheduler
 *****************************************************************************/


// BEGIN: Code from the c_header annotation ArduinoScheduler

#define NB_SOFT_TIMERS 4 // for 4 different timers, 0 to 3. change here to get more or less timers.

// END: Code from the c_header annotation ArduinoScheduler

// Definition of the instance stuct:
struct ArduinoScheduler_Instance {
// Variables for the ID of the instance
int id;
// Variables for the current instance state
int ArduinoScheduler_ArduinoSchedulerStateChart_State;
// Variables for the properties of the instance
uint8_t ArduinoScheduler_interrupt_counter__var;
long ArduinoScheduler_ArduinoSchedulerStateChart_timers__var[NB_SOFT_TIMERS];
long ArduinoScheduler_ArduinoSchedulerStateChart_prev_1sec__var;
};

// Declaration of prototypes outgoing messages:
void ArduinoScheduler_ArduinoSchedulerStateChart_OnEntry(int state, struct ArduinoScheduler_Instance *_instance);
void ArduinoScheduler_handle_arduino_setDigitalHigh(struct ArduinoScheduler_Instance *_instance, uint8_t pin);
void ArduinoScheduler_handle_arduino_serial_print_str(struct ArduinoScheduler_Instance *_instance, char * msg);
void ArduinoScheduler_handle_arduino_setOutput(struct ArduinoScheduler_Instance *_instance, uint8_t pin);
void ArduinoScheduler_handle_arduino_setInput(struct ArduinoScheduler_Instance *_instance, uint8_t pin);
void ArduinoScheduler_handle_arduino_serial_print_dec(struct ArduinoScheduler_Instance *_instance, double num);
void ArduinoScheduler_handle_arduino_usb_print_dec(struct ArduinoScheduler_Instance *_instance, double num);
void ArduinoScheduler_handle_arduino_timer_start(struct ArduinoScheduler_Instance *_instance, uint8_t id, int16_t time);
void ArduinoScheduler_handle_arduino_serial_print_num(struct ArduinoScheduler_Instance *_instance, int16_t num);
void ArduinoScheduler_handle_arduino_usb_print_num(struct ArduinoScheduler_Instance *_instance, int16_t num);
void ArduinoScheduler_handle_arduino_usb_print_str(struct ArduinoScheduler_Instance *_instance, char * msg);
void ArduinoScheduler_handle_arduino_timer_cancel(struct ArduinoScheduler_Instance *_instance, uint8_t id);
void ArduinoScheduler_handle_arduino_setDigitalLow(struct ArduinoScheduler_Instance *_instance, uint8_t pin);
void ArduinoScheduler_handle_arduino_readAnalog(struct ArduinoScheduler_Instance *_instance, uint8_t pin);
void ArduinoScheduler_handle_arduino_readDigital(struct ArduinoScheduler_Instance *_instance, uint8_t pin);
void ArduinoScheduler_handle_polling_setup(struct ArduinoScheduler_Instance *_instance);
void ArduinoScheduler_handle_polling_poll(struct ArduinoScheduler_Instance *_instance);
// Declaration of callbacks for incomming messages:
void register_ArduinoScheduler_send_arduino_ready_listener(void (*_listener)(struct ArduinoScheduler_Instance*));
void register_ArduinoScheduler_send_arduino_4ms_interrupt_listener(void (*_listener)(struct ArduinoScheduler_Instance*));
void register_ArduinoScheduler_send_arduino_100ms_interrupt_listener(void (*_listener)(struct ArduinoScheduler_Instance*));
void register_ArduinoScheduler_send_arduino_1s_poll_listener(void (*_listener)(struct ArduinoScheduler_Instance*));
void register_ArduinoScheduler_send_arduino_timeout_listener(void (*_listener)(struct ArduinoScheduler_Instance*, uint8_t));
void register_ArduinoScheduler_send_arduino_serial_rx_char_listener(void (*_listener)(struct ArduinoScheduler_Instance*, char));
void register_ArduinoScheduler_send_arduino_usb_rx_char_listener(void (*_listener)(struct ArduinoScheduler_Instance*, char));
void register_ArduinoScheduler_send_arduino_readDigitalResponse_listener(void (*_listener)(struct ArduinoScheduler_Instance*, uint8_t, uint8_t));
void register_ArduinoScheduler_send_arduino_readAnalogResponse_listener(void (*_listener)(struct ArduinoScheduler_Instance*, uint8_t, int));

// Definition of the states:
#define ARDUINOSCHEDULER_ARDUINOSCHEDULERSTATECHART_STATE 0
#define ARDUINOSCHEDULER_ARDUINOSCHEDULERSTATECHART_ACTIVE_STATE 1

/*****************************************************************************
 * Implementation for type : ArduinoScheduler
 *****************************************************************************/


// BEGIN: Code from the c_global annotation ArduinoScheduler

struct ArduinoScheduler_Instance *_ArduinoScheduler_instance;
uint8_t interrupt_counter = 0;

// END: Code from the c_global annotation ArduinoScheduler

// Declaration of prototypes:
#ifdef EXTERN_C_PROTOTYPES
extern "C" {
#endif
void ArduinoScheduler_ArduinoSchedulerStateChart_OnExit(int state, struct ArduinoScheduler_Instance *_instance);
void ArduinoScheduler_send_arduino_ready(struct ArduinoScheduler_Instance *_instance);
void ArduinoScheduler_send_arduino_4ms_interrupt(struct ArduinoScheduler_Instance *_instance);
void ArduinoScheduler_send_arduino_100ms_interrupt(struct ArduinoScheduler_Instance *_instance);
void ArduinoScheduler_send_arduino_1s_poll(struct ArduinoScheduler_Instance *_instance);
void ArduinoScheduler_send_arduino_timeout(struct ArduinoScheduler_Instance *_instance, uint8_t id);
void ArduinoScheduler_send_arduino_serial_rx_char(struct ArduinoScheduler_Instance *_instance, char c);
void ArduinoScheduler_send_arduino_usb_rx_char(struct ArduinoScheduler_Instance *_instance, char c);
void ArduinoScheduler_send_arduino_readDigitalResponse(struct ArduinoScheduler_Instance *_instance, uint8_t pin, uint8_t DigitalState);
void ArduinoScheduler_send_arduino_readAnalogResponse(struct ArduinoScheduler_Instance *_instance, uint8_t pin, int res);
void f_ArduinoScheduler_initialize_timer2(struct ArduinoScheduler_Instance *_instance);
SIGNAL(TIMER2_OVF_vect);
#ifdef EXTERN_C_PROTOTYPES
}
#endif

// Declaration of functions:
// Definition of function initialize_timer2
void f_ArduinoScheduler_initialize_timer2(struct ArduinoScheduler_Instance *_instance) {
{
// Store the instance in a global variable so that the interrupt routine can use it
		_ArduinoScheduler_instance = _instance;
		
		// Run timer2 interrupt up counting at 250kHz 
		 TCCR2A = 0;
		 TCCR2B = 1<<CS22 | 0<<CS21 | 0<<CS20;
		
		 //Timer2 Overflow Interrupt Enable
		 TIMSK2 |= 1<<TOIE2;
		
}
}

// Definition of function timer2_overflow_interrupt
SIGNAL(TIMER2_OVF_vect) {
{
TCNT2 = 5; // Leave 250 tics until overflow (1 overflow every 1ms)
interrupt_counter++;
if(interrupt_counter >= 99) {
ArduinoScheduler_send_arduino_100ms_interrupt(_ArduinoScheduler_instance);
interrupt_counter=0;
}
if(interrupt_counter % 4) {
ArduinoScheduler_send_arduino_4ms_interrupt(_ArduinoScheduler_instance);
}
}
}


// On Entry Actions:
void ArduinoScheduler_ArduinoSchedulerStateChart_OnEntry(int state, struct ArduinoScheduler_Instance *_instance) {
switch(state) {
case ARDUINOSCHEDULER_ARDUINOSCHEDULERSTATECHART_STATE:
_instance->ArduinoScheduler_ArduinoSchedulerStateChart_State = ARDUINOSCHEDULER_ARDUINOSCHEDULERSTATECHART_ACTIVE_STATE;
{
Serial.begin(9600);
}
ArduinoScheduler_ArduinoSchedulerStateChart_OnEntry(_instance->ArduinoScheduler_ArduinoSchedulerStateChart_State, _instance);
break;
case ARDUINOSCHEDULER_ARDUINOSCHEDULERSTATECHART_ACTIVE_STATE:
break;
default: break;
}
}

// On Exit Actions:
void ArduinoScheduler_ArduinoSchedulerStateChart_OnExit(int state, struct ArduinoScheduler_Instance *_instance) {
switch(state) {
case ARDUINOSCHEDULER_ARDUINOSCHEDULERSTATECHART_STATE:
ArduinoScheduler_ArduinoSchedulerStateChart_OnExit(_instance->ArduinoScheduler_ArduinoSchedulerStateChart_State, _instance);
break;
case ARDUINOSCHEDULER_ARDUINOSCHEDULERSTATECHART_ACTIVE_STATE:
break;
default: break;
}
}

// Event Handlers for incoming messages:
void ArduinoScheduler_handle_arduino_setDigitalHigh(struct ArduinoScheduler_Instance *_instance, uint8_t pin) {
uint8_t ArduinoScheduler_ArduinoSchedulerStateChart_State_event_consumed = 0;
if (1) {
{
digitalWrite(pin, HIGH);
}
ArduinoScheduler_ArduinoSchedulerStateChart_State_event_consumed = 1;
}
}
void ArduinoScheduler_handle_arduino_serial_print_str(struct ArduinoScheduler_Instance *_instance, char * msg) {
uint8_t ArduinoScheduler_ArduinoSchedulerStateChart_State_event_consumed = 0;
if (1) {
{
Serial.print(msg);
}
ArduinoScheduler_ArduinoSchedulerStateChart_State_event_consumed = 1;
}
}
void ArduinoScheduler_handle_arduino_setOutput(struct ArduinoScheduler_Instance *_instance, uint8_t pin) {
uint8_t ArduinoScheduler_ArduinoSchedulerStateChart_State_event_consumed = 0;
if (1) {
{
pinMode(pin,OUTPUT);
}
ArduinoScheduler_ArduinoSchedulerStateChart_State_event_consumed = 1;
}
}
void ArduinoScheduler_handle_arduino_setInput(struct ArduinoScheduler_Instance *_instance, uint8_t pin) {
uint8_t ArduinoScheduler_ArduinoSchedulerStateChart_State_event_consumed = 0;
if (1) {
{
pinMode(pin,INPUT);
}
ArduinoScheduler_ArduinoSchedulerStateChart_State_event_consumed = 1;
}
}
void ArduinoScheduler_handle_arduino_serial_print_dec(struct ArduinoScheduler_Instance *_instance, double num) {
uint8_t ArduinoScheduler_ArduinoSchedulerStateChart_State_event_consumed = 0;
if (1) {
{
Serial.print(num);
}
ArduinoScheduler_ArduinoSchedulerStateChart_State_event_consumed = 1;
}
}
void ArduinoScheduler_handle_arduino_usb_print_dec(struct ArduinoScheduler_Instance *_instance, double num) {
uint8_t ArduinoScheduler_ArduinoSchedulerStateChart_State_event_consumed = 0;
if (1) {
{
Serial.print(num);
}
ArduinoScheduler_ArduinoSchedulerStateChart_State_event_consumed = 1;
}
}
void ArduinoScheduler_handle_arduino_timer_start(struct ArduinoScheduler_Instance *_instance, uint8_t id, int16_t time) {
uint8_t ArduinoScheduler_ArduinoSchedulerStateChart_State_event_consumed = 0;
if (1) {
{
if(id < NB_SOFT_TIMERS) _instance->ArduinoScheduler_ArduinoSchedulerStateChart_timers__var[id] = millis() + time - 1;
}
ArduinoScheduler_ArduinoSchedulerStateChart_State_event_consumed = 1;
}
}
void ArduinoScheduler_handle_arduino_serial_print_num(struct ArduinoScheduler_Instance *_instance, int16_t num) {
uint8_t ArduinoScheduler_ArduinoSchedulerStateChart_State_event_consumed = 0;
if (1) {
{
Serial.print(num);
}
ArduinoScheduler_ArduinoSchedulerStateChart_State_event_consumed = 1;
}
}
void ArduinoScheduler_handle_arduino_usb_print_num(struct ArduinoScheduler_Instance *_instance, int16_t num) {
uint8_t ArduinoScheduler_ArduinoSchedulerStateChart_State_event_consumed = 0;
if (1) {
{
Serial.print(num);
}
ArduinoScheduler_ArduinoSchedulerStateChart_State_event_consumed = 1;
}
}
void ArduinoScheduler_handle_arduino_usb_print_str(struct ArduinoScheduler_Instance *_instance, char * msg) {
uint8_t ArduinoScheduler_ArduinoSchedulerStateChart_State_event_consumed = 0;
if (1) {
{
Serial.print(msg);
}
ArduinoScheduler_ArduinoSchedulerStateChart_State_event_consumed = 1;
}
}
void ArduinoScheduler_handle_arduino_timer_cancel(struct ArduinoScheduler_Instance *_instance, uint8_t id) {
uint8_t ArduinoScheduler_ArduinoSchedulerStateChart_State_event_consumed = 0;
if (1) {
{
if(id < NB_SOFT_TIMERS) _instance->ArduinoScheduler_ArduinoSchedulerStateChart_timers__var[id] = 0;
}
ArduinoScheduler_ArduinoSchedulerStateChart_State_event_consumed = 1;
}
}
void ArduinoScheduler_handle_arduino_setDigitalLow(struct ArduinoScheduler_Instance *_instance, uint8_t pin) {
uint8_t ArduinoScheduler_ArduinoSchedulerStateChart_State_event_consumed = 0;
if (1) {
{
digitalWrite(pin, LOW);
}
ArduinoScheduler_ArduinoSchedulerStateChart_State_event_consumed = 1;
}
}
void ArduinoScheduler_handle_arduino_readAnalog(struct ArduinoScheduler_Instance *_instance, uint8_t pin) {
uint8_t ArduinoScheduler_ArduinoSchedulerStateChart_State_event_consumed = 0;
if (1) {
{
ArduinoScheduler_send_arduino_readAnalogResponse(_instance, pin, analogRead(pin));
}
ArduinoScheduler_ArduinoSchedulerStateChart_State_event_consumed = 1;
}
}
void ArduinoScheduler_handle_arduino_readDigital(struct ArduinoScheduler_Instance *_instance, uint8_t pin) {
uint8_t ArduinoScheduler_ArduinoSchedulerStateChart_State_event_consumed = 0;
if (1) {
{
if((digitalRead(pin) == HIGH)) {
ArduinoScheduler_send_arduino_readDigitalResponse(_instance, pin, DIGITALSTATE_HIGH);
}
if((digitalRead(pin) == LOW)) {
ArduinoScheduler_send_arduino_readDigitalResponse(_instance, pin, DIGITALSTATE_LOW);
}
}
ArduinoScheduler_ArduinoSchedulerStateChart_State_event_consumed = 1;
}
}
void ArduinoScheduler_handle_polling_setup(struct ArduinoScheduler_Instance *_instance) {
uint8_t ArduinoScheduler_ArduinoSchedulerStateChart_State_event_consumed = 0;
if (1) {
{
f_ArduinoScheduler_initialize_timer2(_instance);
_instance->ArduinoScheduler_ArduinoSchedulerStateChart_prev_1sec__var = millis() + 1000;
ArduinoScheduler_send_arduino_ready(_instance);
}
ArduinoScheduler_ArduinoSchedulerStateChart_State_event_consumed = 1;
}
}
void ArduinoScheduler_handle_polling_poll(struct ArduinoScheduler_Instance *_instance) {
uint8_t ArduinoScheduler_ArduinoSchedulerStateChart_State_event_consumed = 0;
if (1) {
{
long tms = millis();
uint8_t t = 0;
while(t < NB_SOFT_TIMERS) {
if(_instance->ArduinoScheduler_ArduinoSchedulerStateChart_timers__var[t] > 0 && _instance->ArduinoScheduler_ArduinoSchedulerStateChart_timers__var[t] < tms) {
_instance->ArduinoScheduler_ArduinoSchedulerStateChart_timers__var[t] = 0;
ArduinoScheduler_send_arduino_timeout(_instance, t);
}
t = t + 1;
}
if(_instance->ArduinoScheduler_ArduinoSchedulerStateChart_prev_1sec__var < tms) {
_instance->ArduinoScheduler_ArduinoSchedulerStateChart_prev_1sec__var = _instance->ArduinoScheduler_ArduinoSchedulerStateChart_prev_1sec__var + 1000;
ArduinoScheduler_send_arduino_1s_poll(_instance);
}
if(Serial.available() > 0) ArduinoScheduler_send_arduino_usb_rx_char(_instance, (char)Serial.read());
}
ArduinoScheduler_ArduinoSchedulerStateChart_State_event_consumed = 1;
}
}

// Observers for outgoing messages:
void (*ArduinoScheduler_send_arduino_ready_listener)(struct ArduinoScheduler_Instance*)= 0x0;
void register_ArduinoScheduler_send_arduino_ready_listener(void (*_listener)(struct ArduinoScheduler_Instance*)){
ArduinoScheduler_send_arduino_ready_listener = _listener;
}
void ArduinoScheduler_send_arduino_ready(struct ArduinoScheduler_Instance *_instance){
if (ArduinoScheduler_send_arduino_ready_listener != 0x0) ArduinoScheduler_send_arduino_ready_listener(_instance);
}
void (*ArduinoScheduler_send_arduino_4ms_interrupt_listener)(struct ArduinoScheduler_Instance*)= 0x0;
void register_ArduinoScheduler_send_arduino_4ms_interrupt_listener(void (*_listener)(struct ArduinoScheduler_Instance*)){
ArduinoScheduler_send_arduino_4ms_interrupt_listener = _listener;
}
void ArduinoScheduler_send_arduino_4ms_interrupt(struct ArduinoScheduler_Instance *_instance){
if (ArduinoScheduler_send_arduino_4ms_interrupt_listener != 0x0) ArduinoScheduler_send_arduino_4ms_interrupt_listener(_instance);
}
void (*ArduinoScheduler_send_arduino_100ms_interrupt_listener)(struct ArduinoScheduler_Instance*)= 0x0;
void register_ArduinoScheduler_send_arduino_100ms_interrupt_listener(void (*_listener)(struct ArduinoScheduler_Instance*)){
ArduinoScheduler_send_arduino_100ms_interrupt_listener = _listener;
}
void ArduinoScheduler_send_arduino_100ms_interrupt(struct ArduinoScheduler_Instance *_instance){
if (ArduinoScheduler_send_arduino_100ms_interrupt_listener != 0x0) ArduinoScheduler_send_arduino_100ms_interrupt_listener(_instance);
}
void (*ArduinoScheduler_send_arduino_1s_poll_listener)(struct ArduinoScheduler_Instance*)= 0x0;
void register_ArduinoScheduler_send_arduino_1s_poll_listener(void (*_listener)(struct ArduinoScheduler_Instance*)){
ArduinoScheduler_send_arduino_1s_poll_listener = _listener;
}
void ArduinoScheduler_send_arduino_1s_poll(struct ArduinoScheduler_Instance *_instance){
if (ArduinoScheduler_send_arduino_1s_poll_listener != 0x0) ArduinoScheduler_send_arduino_1s_poll_listener(_instance);
}
void (*ArduinoScheduler_send_arduino_timeout_listener)(struct ArduinoScheduler_Instance*, uint8_t)= 0x0;
void register_ArduinoScheduler_send_arduino_timeout_listener(void (*_listener)(struct ArduinoScheduler_Instance*, uint8_t)){
ArduinoScheduler_send_arduino_timeout_listener = _listener;
}
void ArduinoScheduler_send_arduino_timeout(struct ArduinoScheduler_Instance *_instance, uint8_t id){
if (ArduinoScheduler_send_arduino_timeout_listener != 0x0) ArduinoScheduler_send_arduino_timeout_listener(_instance, id);
}
void (*ArduinoScheduler_send_arduino_serial_rx_char_listener)(struct ArduinoScheduler_Instance*, char)= 0x0;
void register_ArduinoScheduler_send_arduino_serial_rx_char_listener(void (*_listener)(struct ArduinoScheduler_Instance*, char)){
ArduinoScheduler_send_arduino_serial_rx_char_listener = _listener;
}
void ArduinoScheduler_send_arduino_serial_rx_char(struct ArduinoScheduler_Instance *_instance, char c){
if (ArduinoScheduler_send_arduino_serial_rx_char_listener != 0x0) ArduinoScheduler_send_arduino_serial_rx_char_listener(_instance, c);
}
void (*ArduinoScheduler_send_arduino_usb_rx_char_listener)(struct ArduinoScheduler_Instance*, char)= 0x0;
void register_ArduinoScheduler_send_arduino_usb_rx_char_listener(void (*_listener)(struct ArduinoScheduler_Instance*, char)){
ArduinoScheduler_send_arduino_usb_rx_char_listener = _listener;
}
void ArduinoScheduler_send_arduino_usb_rx_char(struct ArduinoScheduler_Instance *_instance, char c){
if (ArduinoScheduler_send_arduino_usb_rx_char_listener != 0x0) ArduinoScheduler_send_arduino_usb_rx_char_listener(_instance, c);
}
void (*ArduinoScheduler_send_arduino_readDigitalResponse_listener)(struct ArduinoScheduler_Instance*, uint8_t, uint8_t)= 0x0;
void register_ArduinoScheduler_send_arduino_readDigitalResponse_listener(void (*_listener)(struct ArduinoScheduler_Instance*, uint8_t, uint8_t)){
ArduinoScheduler_send_arduino_readDigitalResponse_listener = _listener;
}
void ArduinoScheduler_send_arduino_readDigitalResponse(struct ArduinoScheduler_Instance *_instance, uint8_t pin, uint8_t DigitalState){
if (ArduinoScheduler_send_arduino_readDigitalResponse_listener != 0x0) ArduinoScheduler_send_arduino_readDigitalResponse_listener(_instance, pin, DigitalState);
}
void (*ArduinoScheduler_send_arduino_readAnalogResponse_listener)(struct ArduinoScheduler_Instance*, uint8_t, int)= 0x0;
void register_ArduinoScheduler_send_arduino_readAnalogResponse_listener(void (*_listener)(struct ArduinoScheduler_Instance*, uint8_t, int)){
ArduinoScheduler_send_arduino_readAnalogResponse_listener = _listener;
}
void ArduinoScheduler_send_arduino_readAnalogResponse(struct ArduinoScheduler_Instance *_instance, uint8_t pin, int res){
if (ArduinoScheduler_send_arduino_readAnalogResponse_listener != 0x0) ArduinoScheduler_send_arduino_readAnalogResponse_listener(_instance, pin, res);
}


/*****************************************************************************
 * Definitions for configuration : ArduinoSketchCfg
 *****************************************************************************/

#define MAX_INSTANCES 32
#define FIFO_SIZE 256

/*********************************
 * Instance IDs and lookup
 *********************************/

void * instances[MAX_INSTANCES];
uint16_t instances_count = 0;

void * instance_by_id(uint16_t id) {
  return instances[id];
}

uint16_t add_instance(void * instance_struct) {
  instances[instances_count] = instance_struct;
  return instances_count++;
}

/******************************************
 * Simple byte FIFO implementation
 ******************************************/

byte fifo[FIFO_SIZE];
int fifo_head = 0;
int fifo_tail = 0;

// Returns the number of byte currently in the fifo
int fifo_byte_length() {
  if (fifo_tail >= fifo_head)
    return fifo_tail - fifo_head;
  return fifo_tail + FIFO_SIZE - fifo_head;
}

// Returns the number of bytes currently available in the fifo
int fifo_byte_available() {
  return FIFO_SIZE - 1 - fifo_byte_length();
}

// Returns true if the fifo is empty
int fifo_empty() {
  return fifo_head == fifo_tail;
}

// Return true if the fifo is full
int fifo_full() {
  return fifo_head == ((fifo_tail + 1) % FIFO_SIZE);
}

// Enqueue 1 byte in the fifo if there is space
// returns 1 for sucess and 0 if the fifo was full
int fifo_enqueue(byte b) {
  int new_tail = (fifo_tail + 1) % FIFO_SIZE;
  if (new_tail == fifo_head) return 0; // the fifo is full
  fifo[fifo_tail] = b;
  fifo_tail = new_tail;
  return 1;
}

// Enqueue 1 byte in the fifo without checking for available space
// The caller should have checked that there is enough space
int _fifo_enqueue(byte b) {
  fifo[fifo_tail] = b;
  fifo_tail = (fifo_tail + 1) % FIFO_SIZE;
}

// Dequeue 1 byte in the fifo.
// The caller should check that the fifo is not empty
byte fifo_dequeue() {
  if (!fifo_empty()) {
    byte result = fifo[fifo_head];
    fifo_head = (fifo_head + 1) % FIFO_SIZE;
    return result;
  }
  return 0;
}

/*
void _fifo_enqueue_ptr(void * ptr) {
  int i;
  ptr_union_t proxy;
  proxy.pointer = ptr;
  for (i = 0; i<PTR_MAX_SIZE; i++) _fifo_enqueue(proxy.buffer[i]);
}

void * _fifo_dequeue_ptr() {
  int i;
  ptr_union_t proxy;
  for (i = 0; i<PTR_MAX_SIZE; i++) proxy.buffer[i] = _fifo_dequeue();
  return proxy.pointer;
}
*/
//Declaration of instance variables
struct ArduinoScheduler_Instance ArduinoSketchCfg_arduinoScheduler_var;
struct Adafruit_1_8pLCDShieldShield_Instance ArduinoSketchCfg_lcd_var;
struct ArduinoSketch_Instance ArduinoSketchCfg_application_var;

// Enqueue of messages ArduinoSketch::button::button_state
void enqueue_ArduinoSketch_send_button_button_state(struct ArduinoSketch_Instance *_instance){
if ( fifo_byte_available() > 4 ) {

_fifo_enqueue( (1 >> 8) & 0xFF );
_fifo_enqueue( 1 & 0xFF );

// ID of the source instance
_fifo_enqueue( (_instance->id >> 8) & 0xFF );
_fifo_enqueue( _instance->id & 0xFF );
}
}
// Enqueue of messages Adafruit_1_8pLCDShieldShield::button::button_state_response
void enqueue_Adafruit_1_8pLCDShieldShield_send_button_button_state_response(struct Adafruit_1_8pLCDShieldShield_Instance *_instance, uint8_t bstate){
if ( fifo_byte_available() > 5 ) {

_fifo_enqueue( (2 >> 8) & 0xFF );
_fifo_enqueue( 2 & 0xFF );

// ID of the source instance
_fifo_enqueue( (_instance->id >> 8) & 0xFF );
_fifo_enqueue( _instance->id & 0xFF );

// parameter bstate
_fifo_enqueue(bstate & 0xFF);
}
}
// Enqueue of messages Adafruit_1_8pLCDShieldShield::button::button_state_change
void enqueue_Adafruit_1_8pLCDShieldShield_send_button_button_state_change(struct Adafruit_1_8pLCDShieldShield_Instance *_instance, uint8_t bstate){
if ( fifo_byte_available() > 5 ) {

_fifo_enqueue( (3 >> 8) & 0xFF );
_fifo_enqueue( 3 & 0xFF );

// ID of the source instance
_fifo_enqueue( (_instance->id >> 8) & 0xFF );
_fifo_enqueue( _instance->id & 0xFF );

// parameter bstate
_fifo_enqueue(bstate & 0xFF);
}
}
// Enqueue of messages Adafruit_1_8pLCDShieldShield::lcd::LCDready
void enqueue_Adafruit_1_8pLCDShieldShield_send_lcd_LCDready(struct Adafruit_1_8pLCDShieldShield_Instance *_instance){
if ( fifo_byte_available() > 4 ) {

_fifo_enqueue( (4 >> 8) & 0xFF );
_fifo_enqueue( 4 & 0xFF );

// ID of the source instance
_fifo_enqueue( (_instance->id >> 8) & 0xFF );
_fifo_enqueue( _instance->id & 0xFF );
}
}

// Dispatch for messages ArduinoScheduler::arduino::4ms_interrupt
void dispatch_ArduinoScheduler_send_arduino_4ms_interrupt(struct ArduinoScheduler_Instance *_instance){
if (_instance == &ArduinoSketchCfg_arduinoScheduler_var) {
}
}
// Dispatch for messages ArduinoScheduler::arduino::ready
void dispatch_ArduinoScheduler_send_arduino_ready(struct ArduinoScheduler_Instance *_instance){
if (_instance == &ArduinoSketchCfg_arduinoScheduler_var) {
Adafruit_1_8pLCDShieldShield_handle_arduino_ready(&ArduinoSketchCfg_lcd_var);
}
}
// Dispatch for messages ArduinoScheduler::arduino::readDigitalResponse
void dispatch_ArduinoScheduler_send_arduino_readDigitalResponse(struct ArduinoScheduler_Instance *_instance, uint8_t pin, uint8_t DigitalState){
if (_instance == &ArduinoSketchCfg_arduinoScheduler_var) {
}
}
// Dispatch for messages ArduinoScheduler::arduino::serial_rx_char
void dispatch_ArduinoScheduler_send_arduino_serial_rx_char(struct ArduinoScheduler_Instance *_instance, char c){
if (_instance == &ArduinoSketchCfg_arduinoScheduler_var) {
}
}
// Dispatch for messages ArduinoScheduler::arduino::1s_poll
void dispatch_ArduinoScheduler_send_arduino_1s_poll(struct ArduinoScheduler_Instance *_instance){
if (_instance == &ArduinoSketchCfg_arduinoScheduler_var) {
}
}
// Dispatch for messages ArduinoScheduler::arduino::100ms_interrupt
void dispatch_ArduinoScheduler_send_arduino_100ms_interrupt(struct ArduinoScheduler_Instance *_instance){
if (_instance == &ArduinoSketchCfg_arduinoScheduler_var) {
ArduinoSketch_handle_arduino_100ms_interrupt(&ArduinoSketchCfg_application_var);
Adafruit_1_8pLCDShieldShield_handle_arduino_100ms_interrupt(&ArduinoSketchCfg_lcd_var);
}
}
// Dispatch for messages ArduinoScheduler::arduino::usb_rx_char
void dispatch_ArduinoScheduler_send_arduino_usb_rx_char(struct ArduinoScheduler_Instance *_instance, char c){
if (_instance == &ArduinoSketchCfg_arduinoScheduler_var) {
}
}
// Dispatch for messages ArduinoScheduler::arduino::readAnalogResponse
void dispatch_ArduinoScheduler_send_arduino_readAnalogResponse(struct ArduinoScheduler_Instance *_instance, uint8_t pin, int res){
if (_instance == &ArduinoSketchCfg_arduinoScheduler_var) {
ArduinoSketch_handle_arduino_readAnalogResponse(&ArduinoSketchCfg_application_var, pin, res);
Adafruit_1_8pLCDShieldShield_handle_arduino_readAnalogResponse(&ArduinoSketchCfg_lcd_var, pin, res);
}
}
// Dispatch for messages ArduinoScheduler::arduino::timeout
void dispatch_ArduinoScheduler_send_arduino_timeout(struct ArduinoScheduler_Instance *_instance, uint8_t id){
if (_instance == &ArduinoSketchCfg_arduinoScheduler_var) {
}
}
// Dispatch for messages ArduinoSketch::button::button_state
void dispatch_ArduinoSketch_send_button_button_state(struct ArduinoSketch_Instance *_instance){
if (_instance == &ArduinoSketchCfg_application_var) {
Adafruit_1_8pLCDShieldShield_handle_button_button_state(&ArduinoSketchCfg_lcd_var);
}
}
// Dispatch for messages ArduinoSketch::lcd::set_cursor
void dispatch_ArduinoSketch_send_lcd_set_cursor(struct ArduinoSketch_Instance *_instance, uint8_t c, uint8_t l){
if (_instance == &ArduinoSketchCfg_application_var) {
Adafruit_1_8pLCDShieldShield_handle_lcd_set_cursor(&ArduinoSketchCfg_lcd_var, c, l);
}
}
// Dispatch for messages ArduinoSketch::lcd::drawRect
void dispatch_ArduinoSketch_send_lcd_drawRect(struct ArduinoSketch_Instance *_instance, uint16_t x, uint16_t y, uint16_t w, uint16_t l, uint16_t col){
if (_instance == &ArduinoSketchCfg_application_var) {
Adafruit_1_8pLCDShieldShield_handle_lcd_drawRect(&ArduinoSketchCfg_lcd_var, x, y, w, l, col);
}
}
// Dispatch for messages ArduinoSketch::lcd::fillRect
void dispatch_ArduinoSketch_send_lcd_fillRect(struct ArduinoSketch_Instance *_instance, uint16_t x, uint16_t y, uint16_t w, uint16_t l, uint16_t col){
if (_instance == &ArduinoSketchCfg_application_var) {
Adafruit_1_8pLCDShieldShield_handle_lcd_fillRect(&ArduinoSketchCfg_lcd_var, x, y, w, l, col);
}
}
// Dispatch for messages ArduinoSketch::lcd::print_dec
void dispatch_ArduinoSketch_send_lcd_print_dec(struct ArduinoSketch_Instance *_instance, double num){
if (_instance == &ArduinoSketchCfg_application_var) {
Adafruit_1_8pLCDShieldShield_handle_lcd_print_dec(&ArduinoSketchCfg_lcd_var, num);
}
}
// Dispatch for messages ArduinoSketch::lcd::print_num
void dispatch_ArduinoSketch_send_lcd_print_num(struct ArduinoSketch_Instance *_instance, int16_t num){
if (_instance == &ArduinoSketchCfg_application_var) {
Adafruit_1_8pLCDShieldShield_handle_lcd_print_num(&ArduinoSketchCfg_lcd_var, num);
}
}
// Dispatch for messages ArduinoSketch::lcd::print_str
void dispatch_ArduinoSketch_send_lcd_print_str(struct ArduinoSketch_Instance *_instance, char * msg){
if (_instance == &ArduinoSketchCfg_application_var) {
Adafruit_1_8pLCDShieldShield_handle_lcd_print_str(&ArduinoSketchCfg_lcd_var, msg);
}
}
// Dispatch for messages ArduinoSketch::lcd::clear
void dispatch_ArduinoSketch_send_lcd_clear(struct ArduinoSketch_Instance *_instance){
if (_instance == &ArduinoSketchCfg_application_var) {
Adafruit_1_8pLCDShieldShield_handle_lcd_clear(&ArduinoSketchCfg_lcd_var);
}
}
// Dispatch for messages ArduinoSketch::lcd::set_bgcolor
void dispatch_ArduinoSketch_send_lcd_set_bgcolor(struct ArduinoSketch_Instance *_instance, uint8_t color){
if (_instance == &ArduinoSketchCfg_application_var) {
}
}
// Dispatch for messages ArduinoSketch::arduino::setDigitalHigh
void dispatch_ArduinoSketch_send_arduino_setDigitalHigh(struct ArduinoSketch_Instance *_instance, uint8_t pin){
if (_instance == &ArduinoSketchCfg_application_var) {
ArduinoScheduler_handle_arduino_setDigitalHigh(&ArduinoSketchCfg_arduinoScheduler_var, pin);
}
}
// Dispatch for messages ArduinoSketch::arduino::serial_print_str
void dispatch_ArduinoSketch_send_arduino_serial_print_str(struct ArduinoSketch_Instance *_instance, char * msg){
if (_instance == &ArduinoSketchCfg_application_var) {
ArduinoScheduler_handle_arduino_serial_print_str(&ArduinoSketchCfg_arduinoScheduler_var, msg);
}
}
// Dispatch for messages ArduinoSketch::arduino::setOutput
void dispatch_ArduinoSketch_send_arduino_setOutput(struct ArduinoSketch_Instance *_instance, uint8_t pin){
if (_instance == &ArduinoSketchCfg_application_var) {
ArduinoScheduler_handle_arduino_setOutput(&ArduinoSketchCfg_arduinoScheduler_var, pin);
}
}
// Dispatch for messages ArduinoSketch::arduino::setInput
void dispatch_ArduinoSketch_send_arduino_setInput(struct ArduinoSketch_Instance *_instance, uint8_t pin){
if (_instance == &ArduinoSketchCfg_application_var) {
ArduinoScheduler_handle_arduino_setInput(&ArduinoSketchCfg_arduinoScheduler_var, pin);
}
}
// Dispatch for messages ArduinoSketch::arduino::serial_print_dec
void dispatch_ArduinoSketch_send_arduino_serial_print_dec(struct ArduinoSketch_Instance *_instance, double num){
if (_instance == &ArduinoSketchCfg_application_var) {
ArduinoScheduler_handle_arduino_serial_print_dec(&ArduinoSketchCfg_arduinoScheduler_var, num);
}
}
// Dispatch for messages ArduinoSketch::arduino::usb_print_dec
void dispatch_ArduinoSketch_send_arduino_usb_print_dec(struct ArduinoSketch_Instance *_instance, double num){
if (_instance == &ArduinoSketchCfg_application_var) {
ArduinoScheduler_handle_arduino_usb_print_dec(&ArduinoSketchCfg_arduinoScheduler_var, num);
}
}
// Dispatch for messages ArduinoSketch::arduino::timer_start
void dispatch_ArduinoSketch_send_arduino_timer_start(struct ArduinoSketch_Instance *_instance, uint8_t id, int16_t time){
if (_instance == &ArduinoSketchCfg_application_var) {
ArduinoScheduler_handle_arduino_timer_start(&ArduinoSketchCfg_arduinoScheduler_var, id, time);
}
}
// Dispatch for messages ArduinoSketch::arduino::serial_print_num
void dispatch_ArduinoSketch_send_arduino_serial_print_num(struct ArduinoSketch_Instance *_instance, int16_t num){
if (_instance == &ArduinoSketchCfg_application_var) {
ArduinoScheduler_handle_arduino_serial_print_num(&ArduinoSketchCfg_arduinoScheduler_var, num);
}
}
// Dispatch for messages ArduinoSketch::arduino::usb_print_num
void dispatch_ArduinoSketch_send_arduino_usb_print_num(struct ArduinoSketch_Instance *_instance, int16_t num){
if (_instance == &ArduinoSketchCfg_application_var) {
ArduinoScheduler_handle_arduino_usb_print_num(&ArduinoSketchCfg_arduinoScheduler_var, num);
}
}
// Dispatch for messages ArduinoSketch::arduino::usb_print_str
void dispatch_ArduinoSketch_send_arduino_usb_print_str(struct ArduinoSketch_Instance *_instance, char * msg){
if (_instance == &ArduinoSketchCfg_application_var) {
ArduinoScheduler_handle_arduino_usb_print_str(&ArduinoSketchCfg_arduinoScheduler_var, msg);
}
}
// Dispatch for messages ArduinoSketch::arduino::timer_cancel
void dispatch_ArduinoSketch_send_arduino_timer_cancel(struct ArduinoSketch_Instance *_instance, uint8_t id){
if (_instance == &ArduinoSketchCfg_application_var) {
ArduinoScheduler_handle_arduino_timer_cancel(&ArduinoSketchCfg_arduinoScheduler_var, id);
}
}
// Dispatch for messages ArduinoSketch::arduino::setDigitalLow
void dispatch_ArduinoSketch_send_arduino_setDigitalLow(struct ArduinoSketch_Instance *_instance, uint8_t pin){
if (_instance == &ArduinoSketchCfg_application_var) {
ArduinoScheduler_handle_arduino_setDigitalLow(&ArduinoSketchCfg_arduinoScheduler_var, pin);
}
}
// Dispatch for messages ArduinoSketch::arduino::readAnalog
void dispatch_ArduinoSketch_send_arduino_readAnalog(struct ArduinoSketch_Instance *_instance, uint8_t pin){
if (_instance == &ArduinoSketchCfg_application_var) {
ArduinoScheduler_handle_arduino_readAnalog(&ArduinoSketchCfg_arduinoScheduler_var, pin);
}
}
// Dispatch for messages ArduinoSketch::arduino::readDigital
void dispatch_ArduinoSketch_send_arduino_readDigital(struct ArduinoSketch_Instance *_instance, uint8_t pin){
if (_instance == &ArduinoSketchCfg_application_var) {
ArduinoScheduler_handle_arduino_readDigital(&ArduinoSketchCfg_arduinoScheduler_var, pin);
}
}
// Dispatch for messages Adafruit_1_8pLCDShieldShield::arduino::serial_print_str
void dispatch_Adafruit_1_8pLCDShieldShield_send_arduino_serial_print_str(struct Adafruit_1_8pLCDShieldShield_Instance *_instance, char * msg){
if (_instance == &ArduinoSketchCfg_lcd_var) {
ArduinoScheduler_handle_arduino_serial_print_str(&ArduinoSketchCfg_arduinoScheduler_var, msg);
}
}
// Dispatch for messages Adafruit_1_8pLCDShieldShield::arduino::readAnalog
void dispatch_Adafruit_1_8pLCDShieldShield_send_arduino_readAnalog(struct Adafruit_1_8pLCDShieldShield_Instance *_instance, uint8_t pin){
if (_instance == &ArduinoSketchCfg_lcd_var) {
ArduinoScheduler_handle_arduino_readAnalog(&ArduinoSketchCfg_arduinoScheduler_var, pin);
}
}
// Dispatch for messages Adafruit_1_8pLCDShieldShield::arduino::setInput
void dispatch_Adafruit_1_8pLCDShieldShield_send_arduino_setInput(struct Adafruit_1_8pLCDShieldShield_Instance *_instance, uint8_t pin){
if (_instance == &ArduinoSketchCfg_lcd_var) {
ArduinoScheduler_handle_arduino_setInput(&ArduinoSketchCfg_arduinoScheduler_var, pin);
}
}
// Dispatch for messages Adafruit_1_8pLCDShieldShield::button::button_state_response
void dispatch_Adafruit_1_8pLCDShieldShield_send_button_button_state_response(struct Adafruit_1_8pLCDShieldShield_Instance *_instance, uint8_t bstate){
if (_instance == &ArduinoSketchCfg_lcd_var) {
}
}
// Dispatch for messages Adafruit_1_8pLCDShieldShield::button::button_state_change
void dispatch_Adafruit_1_8pLCDShieldShield_send_button_button_state_change(struct Adafruit_1_8pLCDShieldShield_Instance *_instance, uint8_t bstate){
if (_instance == &ArduinoSketchCfg_lcd_var) {
}
}
// Dispatch for messages Adafruit_1_8pLCDShieldShield::lcd::LCDready
void dispatch_Adafruit_1_8pLCDShieldShield_send_lcd_LCDready(struct Adafruit_1_8pLCDShieldShield_Instance *_instance){
if (_instance == &ArduinoSketchCfg_lcd_var) {
ArduinoSketch_handle_lcd_LCDready(&ArduinoSketchCfg_application_var);
}
}

void processMessageQueue() {
if (fifo_empty()) return; // return if there is nothing to do

byte mbuf[3];
uint8_t mbufi = 0;

// Read the code of the next port/message in the queue
uint16_t code = fifo_dequeue() << 8;

code += fifo_dequeue();

// Switch to call the appropriate handler
switch(code) {
case 2:
while (mbufi < 3) mbuf[mbufi++] = fifo_dequeue();
dispatch_Adafruit_1_8pLCDShieldShield_send_button_button_state_response((struct Adafruit_1_8pLCDShieldShield_Instance*)instance_by_id((mbuf[0] << 8) + mbuf[1]) /* instance */,
mbuf[2] /* bstate */ );
break;
case 3:
while (mbufi < 3) mbuf[mbufi++] = fifo_dequeue();
dispatch_Adafruit_1_8pLCDShieldShield_send_button_button_state_change((struct Adafruit_1_8pLCDShieldShield_Instance*)instance_by_id((mbuf[0] << 8) + mbuf[1]) /* instance */,
mbuf[2] /* bstate */ );
break;
case 4:
while (mbufi < 2) mbuf[mbufi++] = fifo_dequeue();
dispatch_Adafruit_1_8pLCDShieldShield_send_lcd_LCDready((struct Adafruit_1_8pLCDShieldShield_Instance*)instance_by_id((mbuf[0] << 8) + mbuf[1]) /* instance */);
break;
case 1:
while (mbufi < 2) mbuf[mbufi++] = fifo_dequeue();
dispatch_ArduinoSketch_send_button_button_state((struct ArduinoSketch_Instance*)instance_by_id((mbuf[0] << 8) + mbuf[1]) /* instance */);
break;
}
}

void initialize_configuration_ArduinoSketchCfg() {
// Initialize connectors
register_ArduinoScheduler_send_arduino_ready_listener(dispatch_ArduinoScheduler_send_arduino_ready);
register_ArduinoScheduler_send_arduino_4ms_interrupt_listener(dispatch_ArduinoScheduler_send_arduino_4ms_interrupt);
register_ArduinoScheduler_send_arduino_100ms_interrupt_listener(dispatch_ArduinoScheduler_send_arduino_100ms_interrupt);
register_ArduinoScheduler_send_arduino_1s_poll_listener(dispatch_ArduinoScheduler_send_arduino_1s_poll);
register_ArduinoScheduler_send_arduino_timeout_listener(dispatch_ArduinoScheduler_send_arduino_timeout);
register_ArduinoScheduler_send_arduino_serial_rx_char_listener(dispatch_ArduinoScheduler_send_arduino_serial_rx_char);
register_ArduinoScheduler_send_arduino_usb_rx_char_listener(dispatch_ArduinoScheduler_send_arduino_usb_rx_char);
register_ArduinoScheduler_send_arduino_readDigitalResponse_listener(dispatch_ArduinoScheduler_send_arduino_readDigitalResponse);
register_ArduinoScheduler_send_arduino_readAnalogResponse_listener(dispatch_ArduinoScheduler_send_arduino_readAnalogResponse);
register_ArduinoSketch_send_button_button_state_listener(enqueue_ArduinoSketch_send_button_button_state);
register_ArduinoSketch_send_lcd_print_num_listener(dispatch_ArduinoSketch_send_lcd_print_num);
register_ArduinoSketch_send_lcd_print_dec_listener(dispatch_ArduinoSketch_send_lcd_print_dec);
register_ArduinoSketch_send_lcd_print_str_listener(dispatch_ArduinoSketch_send_lcd_print_str);
register_ArduinoSketch_send_lcd_clear_listener(dispatch_ArduinoSketch_send_lcd_clear);
register_ArduinoSketch_send_lcd_set_cursor_listener(dispatch_ArduinoSketch_send_lcd_set_cursor);
register_ArduinoSketch_send_lcd_set_bgcolor_listener(dispatch_ArduinoSketch_send_lcd_set_bgcolor);
register_ArduinoSketch_send_lcd_fillRect_listener(dispatch_ArduinoSketch_send_lcd_fillRect);
register_ArduinoSketch_send_lcd_drawRect_listener(dispatch_ArduinoSketch_send_lcd_drawRect);
register_ArduinoSketch_send_arduino_timer_start_listener(dispatch_ArduinoSketch_send_arduino_timer_start);
register_ArduinoSketch_send_arduino_timer_cancel_listener(dispatch_ArduinoSketch_send_arduino_timer_cancel);
register_ArduinoSketch_send_arduino_serial_print_str_listener(dispatch_ArduinoSketch_send_arduino_serial_print_str);
register_ArduinoSketch_send_arduino_serial_print_dec_listener(dispatch_ArduinoSketch_send_arduino_serial_print_dec);
register_ArduinoSketch_send_arduino_serial_print_num_listener(dispatch_ArduinoSketch_send_arduino_serial_print_num);
register_ArduinoSketch_send_arduino_usb_print_str_listener(dispatch_ArduinoSketch_send_arduino_usb_print_str);
register_ArduinoSketch_send_arduino_usb_print_dec_listener(dispatch_ArduinoSketch_send_arduino_usb_print_dec);
register_ArduinoSketch_send_arduino_usb_print_num_listener(dispatch_ArduinoSketch_send_arduino_usb_print_num);
register_ArduinoSketch_send_arduino_setDigitalHigh_listener(dispatch_ArduinoSketch_send_arduino_setDigitalHigh);
register_ArduinoSketch_send_arduino_setDigitalLow_listener(dispatch_ArduinoSketch_send_arduino_setDigitalLow);
register_ArduinoSketch_send_arduino_setOutput_listener(dispatch_ArduinoSketch_send_arduino_setOutput);
register_ArduinoSketch_send_arduino_setInput_listener(dispatch_ArduinoSketch_send_arduino_setInput);
register_ArduinoSketch_send_arduino_readDigital_listener(dispatch_ArduinoSketch_send_arduino_readDigital);
register_ArduinoSketch_send_arduino_readAnalog_listener(dispatch_ArduinoSketch_send_arduino_readAnalog);
register_Adafruit_1_8pLCDShieldShield_send_arduino_setInput_listener(dispatch_Adafruit_1_8pLCDShieldShield_send_arduino_setInput);
register_Adafruit_1_8pLCDShieldShield_send_arduino_readAnalog_listener(dispatch_Adafruit_1_8pLCDShieldShield_send_arduino_readAnalog);
register_Adafruit_1_8pLCDShieldShield_send_arduino_serial_print_str_listener(dispatch_Adafruit_1_8pLCDShieldShield_send_arduino_serial_print_str);
register_Adafruit_1_8pLCDShieldShield_send_button_button_state_response_listener(enqueue_Adafruit_1_8pLCDShieldShield_send_button_button_state_response);
register_Adafruit_1_8pLCDShieldShield_send_button_button_state_change_listener(enqueue_Adafruit_1_8pLCDShieldShield_send_button_button_state_change);
register_Adafruit_1_8pLCDShieldShield_send_lcd_LCDready_listener(enqueue_Adafruit_1_8pLCDShieldShield_send_lcd_LCDready);

// Init the ID, state variables and properties for instance ArduinoSketchCfg_arduinoScheduler
ArduinoSketchCfg_arduinoScheduler_var.id = add_instance( (void*) &ArduinoSketchCfg_arduinoScheduler_var);
ArduinoSketchCfg_arduinoScheduler_var.ArduinoScheduler_ArduinoSchedulerStateChart_State = ARDUINOSCHEDULER_ARDUINOSCHEDULERSTATECHART_ACTIVE_STATE;
ArduinoSketchCfg_arduinoScheduler_var.ArduinoScheduler_interrupt_counter__var = 0;

// Init the ID, state variables and properties for instance ArduinoSketchCfg_lcd
ArduinoSketchCfg_lcd_var.id = add_instance( (void*) &ArduinoSketchCfg_lcd_var);
ArduinoSketchCfg_lcd_var.Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_State = ADAFRUIT_1_8PLCDSHIELDSHIELD_RGBLCDSHIELDSM_EMPTY_STATE;
ArduinoSketchCfg_lcd_var.Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_bpin__var = 3;

// Init the ID, state variables and properties for instance ArduinoSketchCfg_application
ArduinoSketchCfg_application_var.id = add_instance( (void*) &ArduinoSketchCfg_application_var);
ArduinoSketchCfg_application_var.ArduinoSketch_ArduinoSketchStateChart_State = ARDUINOSKETCH_ARDUINOSKETCHSTATECHART_INIT_STATE;
ArduinoSketchCfg_application_var.ArduinoSketch_Sensor__var = 0;
ArduinoSketchCfg_application_var.ArduinoSketch_ArduinoSketchStateChart_PLOT_cpt__var = 0;
ArduinoSketchCfg_application_var.ArduinoSketch_ArduinoSketchStateChart_PLOT_MAX__var = 158;

ArduinoSketch_ArduinoSketchStateChart_OnEntry(ARDUINOSKETCH_ARDUINOSKETCHSTATECHART_STATE, &ArduinoSketchCfg_application_var);
Adafruit_1_8pLCDShieldShield_RGBLCDShieldSM_OnEntry(ADAFRUIT_1_8PLCDSHIELDSHIELD_RGBLCDSHIELDSM_STATE, &ArduinoSketchCfg_lcd_var);
ArduinoScheduler_ArduinoSchedulerStateChart_OnEntry(ARDUINOSCHEDULER_ARDUINOSCHEDULERSTATECHART_STATE, &ArduinoSketchCfg_arduinoScheduler_var);
}

/*****************************************************************************
 * Main for configuration : ArduinoSketchCfg
 *****************************************************************************/

void setup() {
initialize_configuration_ArduinoSketchCfg();
ArduinoScheduler_handle_polling_setup(&ArduinoSketchCfg_arduinoScheduler_var);

}

void loop() {
ArduinoScheduler_handle_polling_poll(&ArduinoSketchCfg_arduinoScheduler_var);
Adafruit_1_8pLCDShieldShield_handle_empty_event(&ArduinoSketchCfg_lcd_var);

processMessageQueue();
}